<?php

namespace Database\Seeders;

use App\Models\Cohort;
use App\Models\Course;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        $courses = [
            // Engineering & Development
            [
                'slug' => 'software-development',
                'title' => 'Software Development',
                'category' => 'engineering',
                'description' => 'Master full-stack software development from web fundamentals to production-grade applications. You will build real projects using React, Node.js, PostgreSQL, and modern DevOps practices. This programme is designed for beginners with no prior coding experience who want to land their first developer role within six months.',
                'duration_weeks' => 12,
                'format' => 'cohort',
                'price_ngn' => 150000,
                'price_usd' => 100,
                'scholarship_price_ngn' => 15000,
                'is_published' => true,
                'is_featured' => true,
                'tools_and_technologies' => [
                    ['name' => 'HTML/CSS', 'logo_url' => '/logos/html5.svg'],
                    ['name' => 'JavaScript', 'logo_url' => '/logos/javascript.svg'],
                    ['name' => 'React', 'logo_url' => '/logos/react.svg'],
                    ['name' => 'Node.js', 'logo_url' => '/logos/nodejs.svg'],
                    ['name' => 'PostgreSQL', 'logo_url' => '/logos/postgresql.svg'],
                    ['name' => 'Git', 'logo_url' => '/logos/git.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Software Developer', 'nigeria_ngn' => '₦5M - ₦10M', 'us_usd' => '$95,000 - $145,000', 'global_usd' => '$131,000'],
                    ['role' => 'Full Stack Engineer', 'nigeria_ngn' => '₦6M - ₦12M', 'us_usd' => '$100,000 - $150,000', 'global_usd' => '$140,000'],
                ],
                'what_youll_learn' => [
                    'Build responsive web interfaces using modern HTML, CSS, and React.',
                    'Create robust backend APIs with Node.js and Express.',
                    'Design and query relational databases with PostgreSQL.',
                    'Implement secure authentication and authorisation flows.',
                    'Deploy applications to the cloud using Vercel and Render.',
                    'Work collaboratively using Git and GitHub in an agile workflow.',
                ],
                'faqs' => [
                    ['question' => 'Do I need prior coding experience?', 'answer' => 'No, this programme is designed for absolute beginners. We start with the fundamentals.'],
                    ['question' => 'What kind of computer do I need?', 'answer' => 'Any modern Windows, Mac, or Linux computer with at least 8GB of RAM will be sufficient.'],
                    ['question' => 'Will I get help finding a job?', 'answer' => 'Yes, our career services team will help with your CV, portfolio, and interview preparation.'],
                    ['question' => 'Is the scholarship guaranteed?', 'answer' => 'Scholarships are awarded based on a brief motivation assessment and availability.'],
                ],
                'prerequisites' => 'No prior programming experience required. A working laptop and reliable internet connection are necessary.',
            ],
            [
                'slug' => 'backend-development',
                'title' => 'Backend Development',
                'category' => 'engineering',
                'description' => 'Build robust, scalable server-side applications using Node.js, Express, PostgreSQL, and MongoDB. You will learn API design, authentication, caching with Redis, and deploying to production on cloud platforms. Perfect for those who want to specialise in the engine room of modern software.',
                'duration_weeks' => 10,
                'format' => 'cohort',
                'price_ngn' => 140000,
                'price_usd' => 95,
                'scholarship_price_ngn' => 14000,
                'is_published' => true,
                'is_featured' => false,
                'tools_and_technologies' => [
                    ['name' => 'Node.js', 'logo_url' => '/logos/nodejs.svg'],
                    ['name' => 'PostgreSQL', 'logo_url' => '/logos/postgresql.svg'],
                    ['name' => 'MongoDB', 'logo_url' => '/logos/mongodb.svg'],
                    ['name' => 'Redis', 'logo_url' => '/logos/redis.svg'],
                    ['name' => 'Express', 'logo_url' => '/logos/express.svg'],
                    ['name' => 'Docker', 'logo_url' => '/logos/docker.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Backend Developer', 'nigeria_ngn' => '₦4.5M - ₦9M', 'us_usd' => '$90,000 - $140,000', 'global_usd' => '$125,000'],
                    ['role' => 'API Engineer', 'nigeria_ngn' => '₦5M - ₦10M', 'us_usd' => '$95,000 - $145,000', 'global_usd' => '$130,000'],
                ],
                'what_youll_learn' => [
                    'Architect and build RESTful APIs.',
                    'Manage both SQL and NoSQL databases.',
                    'Implement robust security practices (JWT, hashing, rate limiting).',
                    'Optimise performance using Redis caching.',
                    'Containerise applications with Docker.',
                    'Deploy backend services to cloud platforms.',
                ],
                'faqs' => [
                    ['question' => 'Is this suitable for beginners?', 'answer' => 'We recommend having basic programming knowledge, but the course starts from foundational concepts.'],
                    ['question' => 'Do we learn PHP or Python?', 'answer' => 'This cohort focuses heavily on the JavaScript/TypeScript ecosystem using Node.js.'],
                    ['question' => 'Will I build a portfolio?', 'answer' => 'Yes, you will complete three major backend projects tailored for production use.'],
                ],
                'prerequisites' => 'Basic understanding of programming logic and JavaScript fundamentals.',
            ],
            [
                'slug' => 'frontend-development',
                'title' => 'Frontend Development',
                'category' => 'engineering',
                'description' => 'Build pixel-perfect, accessible, and performant user interfaces using React, TypeScript, and Tailwind CSS. You will cover state management, performance optimisation, and testing — finishing with a portfolio of production-ready projects that demonstrate your craft to employers.',
                'duration_weeks' => 10,
                'format' => 'cohort',
                'price_ngn' => 140000,
                'price_usd' => 95,
                'scholarship_price_ngn' => 14000,
                'is_published' => true,
                'is_featured' => false,
                'tools_and_technologies' => [
                    ['name' => 'React', 'logo_url' => '/logos/react.svg'],
                    ['name' => 'TypeScript', 'logo_url' => '/logos/typescript.svg'],
                    ['name' => 'Tailwind CSS', 'logo_url' => '/logos/tailwindcss.svg'],
                    ['name' => 'Next.js', 'logo_url' => '/logos/nextjs.svg'],
                    ['name' => 'Redux', 'logo_url' => '/logos/redux.svg'],
                    ['name' => 'Figma', 'logo_url' => '/logos/figma.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Frontend Developer', 'nigeria_ngn' => '₦4M - ₦8.5M', 'us_usd' => '$85,000 - $135,000', 'global_usd' => '$118,000'],
                    ['role' => 'React Developer', 'nigeria_ngn' => '₦4.5M - ₦9M', 'us_usd' => '$90,000 - $140,000', 'global_usd' => '$125,000'],
                ],
                'what_youll_learn' => [
                    'Translate UI/UX designs into pixel-perfect web pages.',
                    'Build interactive and accessible single-page applications with React.',
                    'Write type-safe code using TypeScript.',
                    'Manage complex global state effectively.',
                    'Consume RESTful APIs and handle asynchronous data.',
                    'Optimise web performance for mobile and desktop.',
                ],
                'faqs' => [
                    ['question' => 'Do I need design skills?', 'answer' => 'No design skills are required, but you will learn how to implement existing designs from Figma.'],
                    ['question' => 'Is TypeScript hard for beginners?', 'answer' => 'We introduce TypeScript gradually, making it very accessible.'],
                    ['question' => 'What happens if I miss a live class?', 'answer' => 'All live classes are recorded and available on your dashboard within 24 hours.'],
                ],
                'prerequisites' => 'Basic computer literacy. No prior coding experience necessary, though familiarity with HTML/CSS helps.',
            ],
            [
                'slug' => 'devops-engineering',
                'title' => 'DevOps Engineering',
                'category' => 'engineering',
                'description' => 'Learn the tools and practices that keep modern software running reliably at scale. This programme covers Linux systems, Docker, Kubernetes, CI/CD pipelines, Terraform, AWS/GCP, and site reliability engineering. Graduates consistently land roles paying ₦7M–₦13M annually.',
                'duration_weeks' => 14,
                'format' => 'cohort',
                'price_ngn' => 160000,
                'price_usd' => 110,
                'scholarship_price_ngn' => 16000,
                'is_published' => true,
                'is_featured' => false,
                'tools_and_technologies' => [
                    ['name' => 'Docker', 'logo_url' => '/logos/docker.svg'],
                    ['name' => 'Kubernetes', 'logo_url' => '/logos/kubernetes.svg'],
                    ['name' => 'AWS', 'logo_url' => '/logos/aws.svg'],
                    ['name' => 'Terraform', 'logo_url' => '/logos/terraform.svg'],
                    ['name' => 'GitHub Actions', 'logo_url' => '/logos/github-actions.svg'],
                    ['name' => 'Linux', 'logo_url' => '/logos/linux.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'DevOps Engineer', 'nigeria_ngn' => '₦7M - ₦13M', 'us_usd' => '$100,000 - $150,000', 'global_usd' => '$140,000'],
                    ['role' => 'Site Reliability Engineer', 'nigeria_ngn' => '₦8M - ₦15M', 'us_usd' => '$110,000 - $160,000', 'global_usd' => '$145,000'],
                ],
                'what_youll_learn' => [
                    'Master Linux administration and shell scripting.',
                    'Containerise applications using Docker.',
                    'Orchestrate large-scale deployments with Kubernetes.',
                    'Provision infrastructure as code using Terraform.',
                    'Build automated CI/CD pipelines.',
                    'Implement robust logging and monitoring solutions.',
                ],
                'faqs' => [
                    ['question' => 'Is DevOps for beginners?', 'answer' => 'DevOps is best suited for individuals with some background in software development or IT administration.'],
                    ['question' => 'Will I need to pay for AWS?', 'answer' => 'We use free tier resources extensively, but expect to spend about $10-$20 on real-world infrastructure practice.'],
                    ['question' => 'Are certifications included?', 'answer' => 'The curriculum prepares you for AWS certifications, but the exam fees are not included.'],
                ],
                'prerequisites' => 'Basic understanding of software development lifecycle, web servers, and fundamental networking concepts.',
            ],

            // Data & Emerging Technologies
            [
                'slug' => 'data-science',
                'title' => 'Data Science',
                'category' => 'data',
                'description' => 'Move from data to decisions. This programme teaches Python, machine learning with scikit-learn and TensorFlow, statistical modelling, and communicating insights to non-technical stakeholders. You will work on two real-world datasets sourced from African companies.',
                'duration_weeks' => 16,
                'format' => 'cohort',
                'price_ngn' => 170000,
                'price_usd' => 115,
                'scholarship_price_ngn' => 17000,
                'is_published' => true,
                'is_featured' => false,
                'tools_and_technologies' => [
                    ['name' => 'Python', 'logo_url' => '/logos/python.svg'],
                    ['name' => 'TensorFlow', 'logo_url' => '/logos/tensorflow.svg'],
                    ['name' => 'Pandas', 'logo_url' => '/logos/pandas.svg'],
                    ['name' => 'Scikit-learn', 'logo_url' => '/logos/scikit-learn.svg'],
                    ['name' => 'Jupyter', 'logo_url' => '/logos/jupyter.svg'],
                    ['name' => 'SQL', 'logo_url' => '/logos/sql.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Data Scientist', 'nigeria_ngn' => '₦6M - ₦12M', 'us_usd' => '$100,000 - $155,000', 'global_usd' => '$140,000'],
                    ['role' => 'Machine Learning Engineer', 'nigeria_ngn' => '₦7M - ₦14M', 'us_usd' => '$110,000 - $160,000', 'global_usd' => '$150,000'],
                ],
                'what_youll_learn' => [
                    'Perform exploratory data analysis using Python.',
                    'Build and evaluate statistical models.',
                    'Implement machine learning algorithms with Scikit-learn.',
                    'Design deep learning models using TensorFlow.',
                    'Extract and manipulate large datasets using SQL.',
                    'Present findings effectively through data visualisation.',
                ],
                'faqs' => [
                    ['question' => 'Do I need a maths background?', 'answer' => 'High school level mathematics is required. We will teach you the specific statistics needed for data science.'],
                    ['question' => 'What is the difference between Data Science and Analytics?', 'answer' => 'Data Science involves more predictive modelling and machine learning, while Analytics focuses on descriptive insights and business intelligence.'],
                    ['question' => 'Will I learn Python from scratch?', 'answer' => 'Yes, the first month focuses heavily on foundational Python programming.'],
                ],
                'prerequisites' => 'Basic mathematics (statistics/algebra) foundation. No prior coding experience required.',
            ],
            [
                'slug' => 'data-analytics',
                'title' => 'Data Analytics',
                'category' => 'data',
                'description' => 'Turn raw data into actionable business intelligence. Starting from Excel and SQL, you will progress through Power BI, Python (pandas, NumPy), and AI-augmented analytics using ChatGPT and Copilot. The 3-month programme ends with a real-world dataset capstone you can present to employers.',
                'duration_weeks' => 12,
                'format' => 'cohort',
                'price_ngn' => 130000,
                'price_usd' => 88,
                'scholarship_price_ngn' => 13000,
                'is_published' => true,
                'is_featured' => true,
                'tools_and_technologies' => [
                    ['name' => 'SQL', 'logo_url' => '/logos/sql.svg'],
                    ['name' => 'Excel', 'logo_url' => '/logos/excel.svg'],
                    ['name' => 'Power BI', 'logo_url' => '/logos/powerbi.svg'],
                    ['name' => 'Python', 'logo_url' => '/logos/python.svg'],
                    ['name' => 'Tableau', 'logo_url' => '/logos/tableau.svg'],
                    ['name' => 'Copilot', 'logo_url' => '/logos/github-copilot.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Data Analyst', 'nigeria_ngn' => '₦4.8M - ₦8M', 'us_usd' => '$80,000 - $115,000', 'global_usd' => '$121,000'],
                    ['role' => 'Business Intelligence Analyst', 'nigeria_ngn' => '₦5M - ₦9M', 'us_usd' => '$85,000 - $120,000', 'global_usd' => '$125,000'],
                ],
                'what_youll_learn' => [
                    'Clean and organise messy datasets in Excel and SQL.',
                    'Write complex SQL queries to extract business insights.',
                    'Build interactive dashboards using Power BI and Tableau.',
                    'Use Python for advanced data manipulation (pandas).',
                    'Integrate AI tools into your analytical workflows.',
                    'Communicate data narratives to business stakeholders.',
                ],
                'faqs' => [
                    ['question' => 'Is this a coding course?', 'answer' => 'It involves some coding (Python and SQL), but is much lighter on programming than the software engineering tracks.'],
                    ['question' => 'Can I do this on a Mac?', 'answer' => 'Yes, though Power BI is Windows-only, so Mac users will need to use a virtual machine or focus on Tableau.'],
                    ['question' => 'Will I work on real projects?', 'answer' => 'Yes, the capstone project uses genuine datasets from industry partners.'],
                ],
                'prerequisites' => 'Comfort with basic computer operations and spreadsheet software (like Excel or Google Sheets).',
            ],
            [
                'slug' => 'ai-automation',
                'title' => 'AI & Automation',
                'category' => 'data',
                'description' => 'Build intelligent systems and automate repetitive workflows using Python, OpenAI APIs, LangChain, n8n, and Zapier. You will ship three working AI-powered tools during the programme, giving you a portfolio that stands out in a rapidly evolving job market.',
                'duration_weeks' => 12,
                'format' => 'cohort',
                'price_ngn' => 150000,
                'price_usd' => 100,
                'scholarship_price_ngn' => 15000,
                'is_published' => true,
                'is_featured' => false,
                'tools_and_technologies' => [
                    ['name' => 'Python', 'logo_url' => '/logos/python.svg'],
                    ['name' => 'OpenAI', 'logo_url' => '/logos/openai.svg'],
                    ['name' => 'LangChain', 'logo_url' => '/logos/langchain.svg'],
                    ['name' => 'Zapier', 'logo_url' => '/logos/zapier.svg'],
                    ['name' => 'Make', 'logo_url' => '/logos/make.svg'],
                    ['name' => 'n8n', 'logo_url' => '/logos/n8n.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'AI / Automation Engineer', 'nigeria_ngn' => '₦7M - ₦14M', 'us_usd' => '$110,000 - $175,000', 'global_usd' => '$155,000'],
                    ['role' => 'Workflow Consultant', 'nigeria_ngn' => '₦6M - ₦12M', 'us_usd' => '$90,000 - $140,000', 'global_usd' => '$130,000'],
                ],
                'what_youll_learn' => [
                    'Write Python scripts to automate daily tasks.',
                    'Integrate Large Language Models (LLMs) into applications.',
                    'Build complex AI agent workflows using LangChain.',
                    'Connect disparate APIs using Zapier and n8n.',
                    'Design prompt engineering systems for reliable outputs.',
                    'Deploy automation pipelines to cloud servers.',
                ],
                'faqs' => [
                    ['question' => 'Do I need to be a software engineer first?', 'answer' => 'No, but you will learn basic Python. The focus is on integration rather than building apps from scratch.'],
                    ['question' => 'Are API costs included?', 'answer' => 'You will need to cover your own OpenAI/Anthropic API costs, which typically run $5-$10 per month during the course.'],
                    ['question' => 'Is this a future-proof skill?', 'answer' => 'Absolutely. Automation and AI implementation are currently the fastest-growing sectors in tech.'],
                ],
                'prerequisites' => 'A keen analytical mind and basic understanding of how web services interact.',
            ],

            // Design & Creativity
            [
                'slug' => 'product-design',
                'title' => 'Product Design (UI/UX)',
                'category' => 'design',
                'description' => 'Design digital products that people love to use. You will learn user research, wireframing, Figma, interaction design, usability testing, and design systems. The programme culminates in a portfolio of three case studies — the standard requirement for a junior product designer role.',
                'duration_weeks' => 12,
                'format' => 'cohort',
                'price_ngn' => 130000,
                'price_usd' => 88,
                'scholarship_price_ngn' => 13000,
                'is_published' => true,
                'is_featured' => false,
                'tools_and_technologies' => [
                    ['name' => 'Figma', 'logo_url' => '/logos/figma.svg'],
                    ['name' => 'Miro', 'logo_url' => '/logos/miro.svg'],
                    ['name' => 'Notion', 'logo_url' => '/logos/notion.svg'],
                    ['name' => 'Webflow', 'logo_url' => '/logos/webflow.svg'],
                    ['name' => 'Principle', 'logo_url' => '/logos/principle.svg'],
                    ['name' => 'Maze', 'logo_url' => '/logos/maze.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Product Designer', 'nigeria_ngn' => '₦5M - ₦9M', 'us_usd' => '$85,000 - $130,000', 'global_usd' => null],
                    ['role' => 'UX Researcher', 'nigeria_ngn' => '₦4.5M - ₦8M', 'us_usd' => '$80,000 - $125,000', 'global_usd' => null],
                ],
                'what_youll_learn' => [
                    'Conduct qualitative and quantitative user research.',
                    'Create user personas, journey maps, and flowcharts.',
                    'Design wireframes and interactive prototypes in Figma.',
                    'Apply fundamental typography, colour, and layout principles.',
                    'Establish and maintain cohesive design systems.',
                    'Run usability testing sessions to validate concepts.',
                ],
                'faqs' => [
                    ['question' => 'Do I need drawing skills?', 'answer' => 'Not at all. Product design is about problem-solving and systems thinking, not illustration.'],
                    ['question' => 'Do we learn to code?', 'answer' => 'No. We teach you how to hand off designs to developers, but you will not be writing production code.'],
                    ['question' => 'Why three case studies?', 'answer' => 'Industry standard portfolios require at least three comprehensive case studies to demonstrate consistency.'],
                ],
                'prerequisites' => 'Empathy for users and strong problem-solving skills.',
            ],
            [
                'slug' => 'graphics-design',
                'title' => 'Graphics Design',
                'category' => 'design',
                'description' => 'Build a professional graphics design practice using Adobe Photoshop, Illustrator, and InDesign. You will cover brand identity design, typography, print and digital layouts, and client communication. Wenza graduates regularly land roles at agencies and go on to build successful freelance practices.',
                'duration_weeks' => 10,
                'format' => 'cohort',
                'price_ngn' => 110000,
                'price_usd' => 75,
                'scholarship_price_ngn' => 11000,
                'is_published' => true,
                'is_featured' => false,
                'tools_and_technologies' => [
                    ['name' => 'Photoshop', 'logo_url' => '/logos/photoshop.svg'],
                    ['name' => 'Illustrator', 'logo_url' => '/logos/illustrator.svg'],
                    ['name' => 'InDesign', 'logo_url' => '/logos/indesign.svg'],
                    ['name' => 'CorelDRAW', 'logo_url' => '/logos/coreldraw.svg'],
                    ['name' => 'Canva', 'logo_url' => '/logos/canva.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Graphics Designer', 'nigeria_ngn' => '₦3M - ₦6.5M', 'us_usd' => '$55,000 - $90,000', 'global_usd' => '$68,000'],
                    ['role' => 'Brand Identity Designer', 'nigeria_ngn' => '₦4M - ₦7M', 'us_usd' => '$60,000 - $95,000', 'global_usd' => '$75,000'],
                ],
                'what_youll_learn' => [
                    'Master industry-standard Adobe Creative Cloud tools.',
                    'Understand colour theory and typography rules.',
                    'Create distinctive brand identities and logos.',
                    'Design materials for both digital marketing and physical print.',
                    'Manage freelance client communications and contracts.',
                    'Build an eye-catching creative portfolio.',
                ],
                'faqs' => [
                    ['question' => 'Do I get the Adobe software?', 'answer' => 'You must purchase your own Adobe Creative Cloud subscription.'],
                    ['question' => 'Can I use Canva instead?', 'answer' => 'We will touch on Canva for quick workflows, but the core curriculum is built on professional Adobe tools.'],
                    ['question' => 'Is freelance covered?', 'answer' => 'Yes, a full module is dedicated to pricing, proposals, and client management for freelancers.'],
                ],
                'prerequisites' => 'A computer capable of running Adobe CC software smoothly. No prior design experience required.',
            ],
            [
                'slug' => 'content-creation',
                'title' => 'Content Creation',
                'category' => 'design',
                'description' => 'Learn to create compelling content across video, social media, podcasting, and written formats. You will master the craft of storytelling, SEO writing, video editing (DaVinci Resolve, CapCut), and building an audience. The programme teaches you to monetise your skills through brand deals, consulting, and digital products.',
                'duration_weeks' => 8,
                'format' => 'cohort',
                'price_ngn' => 90000,
                'price_usd' => 60,
                'scholarship_price_ngn' => 9000,
                'is_published' => true,
                'is_featured' => false,
                'tools_and_technologies' => [
                    ['name' => 'CapCut', 'logo_url' => '/logos/capcut.svg'],
                    ['name' => 'DaVinci Resolve', 'logo_url' => '/logos/davinci.svg'],
                    ['name' => 'WordPress', 'logo_url' => '/logos/wordpress.svg'],
                    ['name' => 'Notion', 'logo_url' => '/logos/notion.svg'],
                    ['name' => 'Substack', 'logo_url' => '/logos/substack.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Content Creator', 'nigeria_ngn' => '₦2.5M - ₦6M', 'us_usd' => '$45,000 - $85,000', 'global_usd' => '$62,000'],
                    ['role' => 'Social Media Manager', 'nigeria_ngn' => '₦3M - ₦6.5M', 'us_usd' => '$50,000 - $85,000', 'global_usd' => '$65,000'],
                ],
                'what_youll_learn' => [
                    'Script and structure engaging video and audio content.',
                    'Edit high-retention short-form videos in CapCut.',
                    'Perform professional colour correction and editing in DaVinci Resolve.',
                    'Write SEO-optimised blog posts and newsletters.',
                    'Grow and engage social media audiences organically.',
                    'Pitch and negotiate brand sponsorship deals.',
                ],
                'faqs' => [
                    ['question' => 'Do I need an expensive camera?', 'answer' => 'No. A modern smartphone is all you need to start the video modules.'],
                    ['question' => 'Will my followers grow instantly?', 'answer' => 'Content creation requires consistency. We provide the strategy; you provide the reps.'],
                    ['question' => 'Is this only for influencers?', 'answer' => 'Not at all. Businesses desperately need skilled in-house creators for corporate channels.'],
                ],
                'prerequisites' => 'A smartphone capable of shooting decent 1080p video, and a passion for storytelling.',
            ],

            // Management & Business
            [
                'slug' => 'product-management',
                'title' => 'Product Management',
                'category' => 'business',
                'description' => 'Learn what it takes to define, build, and launch great products. This 11-module programme covers market research, product vision, Agile methodology, user-centred design, data analytics, and stakeholder management. Wenza PM graduates earn ₦7M–₦12M annually at top Nigerian tech companies.',
                'duration_weeks' => 12,
                'format' => 'cohort',
                'price_ngn' => 150000,
                'price_usd' => 100,
                'scholarship_price_ngn' => 15000,
                'is_published' => true,
                'is_featured' => true,
                'tools_and_technologies' => [
                    ['name' => 'Jira', 'logo_url' => '/logos/jira.svg'],
                    ['name' => 'Linear', 'logo_url' => '/logos/linear.svg'],
                    ['name' => 'Mixpanel', 'logo_url' => '/logos/mixpanel.svg'],
                    ['name' => 'Amplitude', 'logo_url' => '/logos/amplitude.svg'],
                    ['name' => 'Figma', 'logo_url' => '/logos/figma.svg'],
                    ['name' => 'Notion', 'logo_url' => '/logos/notion.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Product Manager', 'nigeria_ngn' => '₦7M - ₦12M', 'us_usd' => '$105,000 - $155,000', 'global_usd' => null],
                    ['role' => 'Associate Product Manager', 'nigeria_ngn' => '₦5M - ₦8M', 'us_usd' => '$85,000 - $110,000', 'global_usd' => null],
                ],
                'what_youll_learn' => [
                    'Translate business goals into actionable product specifications.',
                    'Prioritise features using frameworks like RICE and MoSCoW.',
                    'Write clear Product Requirements Documents (PRDs).',
                    'Manage Agile sprints and lead development teams.',
                    'Define and track success metrics (AARRR funnel).',
                    'Conduct user interviews to discover commercial opportunities.',
                ],
                'faqs' => [
                    ['question' => 'Do I need to be a programmer to be a PM?', 'answer' => 'No, PMs focus on the "what" and "why", not the "how". However, technical literacy helps.'],
                    ['question' => 'Is this different from project management?', 'answer' => 'Yes. Project management is about delivery schedules and scope; Product management is about strategic value and user needs.'],
                    ['question' => 'How big are the cohorts?', 'answer' => 'Product Management cohorts are capped at 30 to ensure quality feedback on your PRDs.'],
                ],
                'prerequisites' => 'Strong communication skills and an analytical mindset. Business or tech background is helpful but not required.',
            ],
            [
                'slug' => 'project-management',
                'title' => 'Project Management',
                'category' => 'business',
                'description' => 'Become a certified project manager using PMBOK, Agile, and Scrum frameworks. You will learn how to scope, plan, execute, and close projects across industries. The programme prepares you for PMP and CAPM certifications and connects you with hiring partners actively seeking project management talent.',
                'duration_weeks' => 10,
                'format' => 'cohort',
                'price_ngn' => 120000,
                'price_usd' => 80,
                'scholarship_price_ngn' => 12000,
                'is_published' => true,
                'is_featured' => false,
                'tools_and_technologies' => [
                    ['name' => 'Asana', 'logo_url' => '/logos/asana.svg'],
                    ['name' => 'Monday.com', 'logo_url' => '/logos/monday.svg'],
                    ['name' => 'Jira', 'logo_url' => '/logos/jira.svg'],
                    ['name' => 'Trello', 'logo_url' => '/logos/trello.svg'],
                    ['name' => 'MS Project', 'logo_url' => '/logos/msproject.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Project Manager', 'nigeria_ngn' => '₦6M - ₦11M', 'us_usd' => '$90,000 - $135,000', 'global_usd' => '$110,000'],
                    ['role' => 'Scrum Master', 'nigeria_ngn' => '₦6M - ₦10M', 'us_usd' => '$95,000 - $130,000', 'global_usd' => '$115,000'],
                ],
                'what_youll_learn' => [
                    'Define project scope, budgets, and timelines accurately.',
                    'Apply both Waterfall (PMBOK) and Agile (Scrum) methodologies.',
                    'Identify and mitigate project risks effectively.',
                    'Manage resources and resolve team conflicts.',
                    'Communicate status updates clearly to executive stakeholders.',
                    'Prepare for globally recognised PM certifications.',
                ],
                'faqs' => [
                    ['question' => 'Does this course include PMP certification?', 'answer' => 'It prepares you with the required educational hours, but you must register and pay for the PMI exams separately.'],
                    ['question' => 'Is this only for tech projects?', 'answer' => 'No, the principles learned here apply to construction, marketing, events, and tech.'],
                    ['question' => 'What tooling do we focus on?', 'answer' => 'We cover Jira extensively for Agile, and Asana/Monday for general project tracking.'],
                ],
                'prerequisites' => 'Highly organised with excellent written and verbal communication skills.',
            ],
            [
                'slug' => 'virtual-assistant',
                'title' => 'Virtual Assistant',
                'category' => 'business',
                'description' => 'Launch a career as a professional virtual assistant serving clients globally. You will learn executive assistance, calendar management, email management, bookkeeping basics, social media management, and tools like Notion, Asana, and Slack. Wenza VA graduates earn $800–$2,500 per month working remotely.',
                'duration_weeks' => 8,
                'format' => 'cohort',
                'price_ngn' => 90000,
                'price_usd' => 60,
                'scholarship_price_ngn' => 9000,
                'is_published' => true,
                'is_featured' => false,
                'tools_and_technologies' => [
                    ['name' => 'Google Workspace', 'logo_url' => '/logos/google.svg'],
                    ['name' => 'Slack', 'logo_url' => '/logos/slack.svg'],
                    ['name' => 'Notion', 'logo_url' => '/logos/notion.svg'],
                    ['name' => 'Calendly', 'logo_url' => '/logos/calendly.svg'],
                    ['name' => 'Zoom', 'logo_url' => '/logos/zoom.svg'],
                    ['name' => 'QuickBooks', 'logo_url' => '/logos/quickbooks.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Virtual Assistant', 'nigeria_ngn' => '₦2M - ₦5M', 'us_usd' => '$35,000 - $65,000', 'global_usd' => '$48,000'],
                    ['role' => 'Executive Assistant', 'nigeria_ngn' => '₦3M - ₦6M', 'us_usd' => '$45,000 - $75,000', 'global_usd' => '$55,000'],
                ],
                'what_youll_learn' => [
                    'Manage complex calendars and schedule international meetings.',
                    'Handle executive email inboxes efficiently (inbox zero).',
                    'Perform basic remote bookkeeping and data entry.',
                    'Organise files, wikis, and documentation in Notion.',
                    'Draft professional corporate communications.',
                    'Find, pitch, and secure international remote clients.',
                ],
                'faqs' => [
                    ['question' => 'How quickly can I find clients?', 'answer' => 'Many students land their first freelance client before the 8-week cohort is finished.'],
                    ['question' => 'Is a laptop absolutely necessary?', 'answer' => 'Yes. While some tasks can be done on mobile, a VA requires a computer for full productivity.'],
                    ['question' => 'Does Wenza hire VAs?', 'answer' => 'We occasionally hire from our top graduates, but our focus is teaching you to freelance globally.'],
                ],
                'prerequisites' => 'Basic computer literacy, fluency in English, and strong organisational skills.',
            ],
            [
                'slug' => 'digital-marketing',
                'title' => 'Digital Marketing',
                'category' => 'business',
                'description' => 'Drive real business growth through digital channels. This programme covers SEO, Google Ads, Meta advertising, email marketing, marketing analytics, and conversion optimisation. You will manage a live ad campaign during the course, giving you verifiable proof of results for your portfolio.',
                'duration_weeks' => 10,
                'format' => 'cohort',
                'price_ngn' => 120000,
                'price_usd' => 80,
                'scholarship_price_ngn' => 12000,
                'is_published' => true,
                'is_featured' => false,
                'tools_and_technologies' => [
                    ['name' => 'Google Ads', 'logo_url' => '/logos/googleads.svg'],
                    ['name' => 'Meta Ads', 'logo_url' => '/logos/meta.svg'],
                    ['name' => 'Google Analytics', 'logo_url' => '/logos/analytics.svg'],
                    ['name' => 'Mailchimp', 'logo_url' => '/logos/mailchimp.svg'],
                    ['name' => 'SEMrush', 'logo_url' => '/logos/semrush.svg'],
                    ['name' => 'HubSpot', 'logo_url' => '/logos/hubspot.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Digital Marketer', 'nigeria_ngn' => '₦3M - ₦7M', 'us_usd' => '$55,000 - $95,000', 'global_usd' => '$72,000'],
                    ['role' => 'Performance Marketer', 'nigeria_ngn' => '₦4M - ₦8.5M', 'us_usd' => '$65,000 - $110,000', 'global_usd' => '$80,000'],
                ],
                'what_youll_learn' => [
                    'Launch and optimise profitable Google and Meta ad campaigns.',
                    'Implement SEO strategies to drive organic traffic.',
                    'Build high-converting email marketing sequences.',
                    'Analyse user data using Google Analytics 4 (GA4).',
                    'Design landing pages that maximise conversion rates.',
                    'Construct comprehensive go-to-market strategies.',
                ],
                'faqs' => [
                    ['question' => 'Do I need to spend my own money on ads?', 'answer' => 'Wenza provides a small sandbox budget for learning, but professional certification requires managing real spend.'],
                    ['question' => 'Is this course focused on strategy or execution?', 'answer' => 'Both. You will learn the high-level strategy and the button-clicks required to execute it.'],
                    ['question' => 'Can I use this for my own business?', 'answer' => 'Absolutely. It is highly recommended for entrepreneurs wanting to drive sales.'],
                ],
                'prerequisites' => 'A basic understanding of social media platforms and an interest in consumer behaviour.',
            ],

            // Security
            [
                'slug' => 'cybersecurity',
                'title' => 'Cybersecurity',
                'category' => 'security',
                'description' => 'Train as a professional cybersecurity analyst defending against the attacks that cost African businesses billions annually. Over four months you will cover networking and Linux foundations, defensive security (Splunk, Wazuh, Wireshark), offensive security (Kali Linux, Metasploit, OWASP Top 10), and a "Defend & Respond" capstone. Graduates earn ₦6M–₦10M annually.',
                'duration_weeks' => 16,
                'format' => 'cohort',
                'price_ngn' => 180000,
                'price_usd' => 120,
                'scholarship_price_ngn' => 18000,
                'is_published' => true,
                'is_featured' => true,
                'tools_and_technologies' => [
                    ['name' => 'Linux', 'logo_url' => '/logos/linux.svg'],
                    ['name' => 'Wireshark', 'logo_url' => '/logos/wireshark.svg'],
                    ['name' => 'Splunk', 'logo_url' => '/logos/splunk.svg'],
                    ['name' => 'Kali Linux', 'logo_url' => '/logos/kali.svg'],
                    ['name' => 'Metasploit', 'logo_url' => '/logos/metasploit.svg'],
                    ['name' => 'Wazuh', 'logo_url' => '/logos/wazuh.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Cybersecurity Analyst', 'nigeria_ngn' => '₦6M - ₦10M', 'us_usd' => '$90,000 - $135,000', 'global_usd' => '$145,000'],
                    ['role' => 'SOC Analyst', 'nigeria_ngn' => '₦5M - ₦9M', 'us_usd' => '$85,000 - $120,000', 'global_usd' => '$130,000'],
                ],
                'what_youll_learn' => [
                    'Analyse network traffic to detect anomalies using Wireshark.',
                    'Configure and monitor SIEM solutions (Splunk).',
                    'Conduct vulnerability assessments and penetration tests.',
                    'Secure Linux and Windows operating systems.',
                    'Respond to and mitigate active cyber threats.',
                    'Understand compliance frameworks (ISO 27001, GDPR).',
                ],
                'faqs' => [
                    ['question' => 'Is hacking legal?', 'answer' => 'We teach ethical hacking (white-hat) strictly for defensive purposes and against authorised targets in a lab environment.'],
                    ['question' => 'Do I need a powerful computer?', 'answer' => 'You will need at least 8GB (preferably 16GB) of RAM to run virtual machines smoothly.'],
                    ['question' => 'Will this prepare me for CompTIA Sec+?', 'answer' => 'Yes, the curriculum maps strongly to the CompTIA Security+ certification objectives.'],
                ],
                'prerequisites' => 'Strong computer literacy. Basic networking or IT background is beneficial but not strictly required.',
            ],

            // Cloud Engineering
            [
                'slug' => 'cloud-engineering',
                'title' => 'Cloud Engineering',
                'category' => 'engineering',
                'description' => 'Design, build, and manage scalable cloud infrastructure on AWS and Azure. This programme covers cloud architecture, serverless computing, containerisation with Docker and Kubernetes, infrastructure-as-code with Terraform, and cost optimisation. Graduates are prepared for AWS Solutions Architect and Azure Administrator certifications.',
                'duration_weeks' => 14,
                'format' => 'cohort',
                'price_ngn' => 170000,
                'price_usd' => 115,
                'scholarship_price_ngn' => 17000,
                'is_published' => true,
                'is_featured' => false,
                'tools_and_technologies' => [
                    ['name' => 'AWS', 'logo_url' => '/logos/aws.svg'],
                    ['name' => 'Azure', 'logo_url' => '/logos/azure.svg'],
                    ['name' => 'Terraform', 'logo_url' => '/logos/terraform.svg'],
                    ['name' => 'Docker', 'logo_url' => '/logos/docker.svg'],
                    ['name' => 'Kubernetes', 'logo_url' => '/logos/kubernetes.svg'],
                    ['name' => 'Linux', 'logo_url' => '/logos/linux.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Cloud Engineer', 'nigeria_ngn' => '₦7M - ₦13M', 'us_usd' => '$105,000 - $160,000', 'global_usd' => '$145,000'],
                    ['role' => 'Cloud Solutions Architect', 'nigeria_ngn' => '₦9M - ₦16M', 'us_usd' => '$120,000 - $180,000', 'global_usd' => '$155,000'],
                ],
                'what_youll_learn' => [
                    'Architect highly available systems across AWS and Azure.',
                    'Manage identity, access, and security in the cloud.',
                    'Deploy applications using containers and orchestration.',
                    'Automate infrastructure provisioning with Terraform.',
                    'Optimise cloud expenditure using right-sizing strategies.',
                    'Implement serverless architectures and managed databases.',
                ],
                'faqs' => [
                    ['question' => 'How is this different from DevOps?', 'answer' => 'Cloud Engineering focuses heavily on architectural design and cloud-native services, while DevOps focuses more on CI/CD pipelines and deployment automation. There is overlap.'],
                    ['question' => 'Which cloud provider do we focus on?', 'answer' => 'The curriculum is heavily weighted heavily towards AWS, but covers multi-cloud concepts and Azure foundations.'],
                    ['question' => 'Is this a beginner course?', 'answer' => 'No. You should have a solid grasp of basic networking, Linux, and general computing concepts before starting.'],
                ],
                'prerequisites' => 'Fundamental understanding of networking (TCP/IP), Linux command line, and basic scripting.',
            ],
        ];

        foreach ($courses as $courseData) {
            $course = Course::updateOrCreate(
                ['slug' => $courseData['slug']],
                $courseData
            );

            // Seed a starter cohort for each course
            Cohort::firstOrCreate(
                [
                    'course_id' => $course->id,
                    'name' => 'Phoenix Cohort',
                ],
                [
                    'start_date' => now()->addDays(30)->toDateString(),
                    'end_date' => now()->addDays(30 + ($courseData['duration_weeks'] * 7))->toDateString(),
                    'capacity' => 30,
                    'status' => 'upcoming',
                ]
            );
        }
    }
}
