<?php

namespace Database\Seeders;

use App\Models\Course;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        $courses = [
            // Engineering & Development
            [
                'slug' => 'software-development',
                'title' => 'Software Development',
                'category' => 'engineering',
                'description' => 'Master the entire development stack from frontend to backend. You will learn HTML, CSS, JavaScript, React, Node.js, and PostgreSQL through hands-on projects. We focus on industry best practices, agile methodologies, and preparing you for a high-growth career as a software engineer in just 12 weeks.',
                'duration_weeks' => 12,
                'format' => 'cohort',
                'price_ngn' => 150000,
                'price_usd' => 100,
                'scholarship_price_ngn' => 15000,
                'is_published' => true,
                'is_featured' => true,
                'tools_and_technologies' => [
                    ['name' => 'React', 'logo_url' => '/logos/react.svg'],
                    ['name' => 'Node.js', 'logo_url' => '/logos/nodejs.svg'],
                    ['name' => 'PostgreSQL', 'logo_url' => '/logos/postgresql.svg'],
                    ['name' => 'Tailwind CSS', 'logo_url' => '/logos/tailwind.svg'],
                    ['name' => 'Git', 'logo_url' => '/logos/git.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Full Stack Developer', 'nigeria_ngn' => '₦4M - ₦8M', 'us_usd' => '$80,000 - $125,000', 'global_usd' => '$110,000'],
                    ['role' => 'Software Engineer', 'nigeria_ngn' => '₦5M - ₦10M', 'us_usd' => '$95,000 - $150,000', 'global_usd' => '$135,000'],
                ],
                'outcomes' => [
                    'Build and deploy production-grade full-stack applications.',
                    'Master modern frontend development with React and Tailwind CSS.',
                    'Design scalable relational database schemas.',
                    'Implement secure user authentication and authorisation systems.',
                    'Architect robust backend services using Node.js.',
                    'Collaborate in professional engineering teams using Git/GitHub.',
                    'Optimise web applications for speed, accessibility, and SEO.',
                ],
                'curriculum' => [
                    ['week' => 1, 'title' => 'Web Foundations', 'topics' => ['Semantic HTML', 'CSS Fundamentals', 'Flexbox & Grid', 'Responsive Design']],
                    ['week' => 2, 'title' => 'JavaScript Deep Dive', 'topics' => ['ES6+ Syntax', 'Asynchronous JS', 'DOM Manipulation', 'Local Storage']],
                    ['week' => 3, 'title' => 'React Basics', 'topics' => ['Components & Props', 'State Management', 'Hooks (useState, useEffect)', 'Handling Forms']],
                    ['week' => 4, 'title' => 'Advanced React', 'topics' => ['Context API', 'React Router', 'Custom Hooks', 'Performance Optimisation']],
                    ['week' => 5, 'title' => 'Backend with Node.js', 'topics' => ['Express Framework', 'Middleware', 'Routing', 'File Systems']],
                    ['week' => 6, 'title' => 'Database Design', 'topics' => ['SQL Basics', 'PostgreSQL Setup', 'Relationships (One-to-Many, Many-to-Many)', 'Indexing']],
                    ['week' => 7, 'title' => 'Authentication', 'topics' => ['JWT Tokens', 'Password Hashing', 'OAuth 2.0', 'Session Management']],
                    ['week' => 8, 'title' => 'API Integration', 'topics' => ['RESTful Principles', 'CRUD Operations', 'Error Handling', 'Input Validation']],
                    ['week' => 9, 'title' => 'Frontend & Backend Sync', 'topics' => ['Full Stack Architecture', 'Managing State across Client/Server', 'CORS & Security']],
                    ['week' => 10, 'title' => 'Testing & Debugging', 'topics' => ['Unit Testing with Jest', 'Integration Testing', 'Chrome DevTools Mastery']],
                    ['week' => 11, 'title' => 'Cloud Deployment', 'topics' => ['CI/CD Pipelines', 'Vercel & Render', 'Environment Variables', 'Monitoring']],
                    ['week' => 12, 'title' => 'Capstone Project', 'topics' => ['Project Scoping', 'Agile Sprints', 'Final Build & Demo', 'Technical Interview Prep']],
                ],
                'about_mdx' => "Master the art of full-stack development in our flagship programme. This intensive **12-week track** takes you from writing your first line of HTML to deploying complex, production-ready applications to the cloud.\n\nYou will work with the industry's most in-demand technologies: **React, Node.js, and PostgreSQL**. More importantly, you will learn the mental models of a senior engineer—how to break down problems, architect systems, and write clean, maintainable code.\n\nOur graduates don't just leave with a certificate; they leave with a portfolio of real-world projects and the confidence to ace technical interviews at global tech companies.",
                'faqs' => [
                    ['question' => 'Do I need prior coding experience?', 'answer' => 'No, this programme is designed for absolute beginners. We start with the fundamentals.'],
                    ['question' => 'What kind of computer do I need?', 'answer' => 'Any modern Windows, Mac, or Linux computer with at least 8GB of RAM will be sufficient.'],
                    ['question' => 'Will I get help finding a job?', 'answer' => 'Yes, our career services team will help with your CV, portfolio, and interview preparation.'],
                    ['question' => 'Is the scholarship guaranteed?', 'answer' => 'Scholarships are awarded based on a brief motivation assessment and availability.'],
                    ['question' => 'How many hours per week are required?', 'answer' => 'Expect to commit at least 20-25 hours per week including classes and self-study.'],
                    ['question' => 'Are there any hidden costs?', 'answer' => 'No, the tuition covers all curriculum materials and mentor sessions.'],
                ],
                'prerequisites' => 'No prior programming experience required. A working laptop and reliable internet connection are necessary.',
            ],
            [
                'slug' => 'backend-development',
                'title' => 'Backend Development',
                'category' => 'engineering',
                'description' => 'Build robust, scalable server-side applications using Node.js, Express, PostgreSQL, and MongoDB. You will learn API design, authentication, caching with Redis, and deploying to production on cloud platforms. Perfect for those who want to specialise in the engine room of modern software.',
                'duration_weeks' => 10,
                'format' => 'cohort',
                'price_ngn' => 140000,
                'price_usd' => 95,
                'scholarship_price_ngn' => 14000,
                'is_published' => true,
                'is_featured' => false,
                'tools_and_technologies' => [
                    ['name' => 'Node.js', 'logo_url' => '/logos/nodejs.svg'],
                    ['name' => 'PostgreSQL', 'logo_url' => '/logos/postgresql.svg'],
                    ['name' => 'MongoDB', 'logo_url' => '/logos/mongodb.svg'],
                    ['name' => 'Redis', 'logo_url' => '/logos/redis.svg'],
                    ['name' => 'Express', 'logo_url' => '/logos/express.svg'],
                    ['name' => 'Docker', 'logo_url' => '/logos/docker.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Backend Developer', 'nigeria_ngn' => '₦4.5M - ₦9M', 'us_usd' => '$90,000 - $140,000', 'global_usd' => '$125,000'],
                    ['role' => 'API Engineer', 'nigeria_ngn' => '₦5M - ₦10M', 'us_usd' => '$95,000 - $145,000', 'global_usd' => '$130,000'],
                ],
                'outcomes' => [
                    'Design and implement secure RESTful and GraphQL APIs.',
                    'Master SQL (PostgreSQL) and NoSQL (MongoDB) database management.',
                    'Apply advanced security patterns including JWT and OAuth.',
                    'Optimise high-traffic systems using Redis caching.',
                    'Containerise services using Docker for consistent environments.',
                    'Build scalable microservices architectures.',
                    'Deploy and monitor backend infrastructure on AWS or GCP.',
                ],
                'curriculum' => [
                    ['week' => 1, 'title' => 'Server Environments', 'topics' => ['Node.js Architecture', 'NPM & Versioning', 'Event Loop', 'Async Patterns']],
                    ['week' => 2, 'title' => 'Express Framework', 'topics' => ['Middleware', 'Routing', 'Error Handling', 'Templates']],
                    ['week' => 3, 'title' => 'Relational Databases', 'topics' => ['PostgreSQL Schema Design', 'Complex Queries', 'ORM with Prisma', 'Migrations']],
                    ['week' => 4, 'title' => 'NoSQL Databases', 'topics' => ['MongoDB Foundations', 'Document Modeling', 'Aggregation Framework', 'Mongoose']],
                    ['week' => 5, 'title' => 'Security & Auth', 'topics' => ['Bcrypt', 'JWT Strategies', 'Passport.js', 'Role-Based Access Control']],
                    ['week' => 6, 'title' => 'Performance & Caching', 'topics' => ['Redis Setup', 'Cache Invalidation', 'Rate Limiting', 'Optimising Queries']],
                    ['week' => 7, 'title' => 'Testing & Quality', 'topics' => ['Unit Testing with Vitest', 'Integration Testing APIs', 'Mocking Databases']],
                    ['week' => 8, 'title' => 'Containerisation', 'topics' => ['Docker Basics', 'Dockerfile Design', 'Docker Compose', 'Development Containers']],
                    ['week' => 9, 'title' => 'Advanced Patterns', 'topics' => ['WebSockets for Real-time', 'Job Queues (BullMQ)', 'Microservices Communication']],
                    ['week' => 10, 'title' => 'Production & Monitoring', 'topics' => ['CI/CD for Backend', 'Cloud Run & Docker Hub', 'Logging (Winston)', 'Datadog Basics']],
                ],
                'about_mdx' => "Backend development is the engine room of the modern web. This programme is designed for developers who want to dive deep into **architecture, security, and performance**.\n\nYou'll go far beyond basic CRUD apps. You'll learn to handle **real-world scale** using Redis for caching, Docker for containerisation, and both SQL and NoSQL databases for diverse data needs.\n\nBy the end of this 10-week cohort, you'll be capable of architecting backend systems that are robust, secure, and ready to serve millions of users.",
                'faqs' => [
                    ['question' => 'Is this suitable for beginners?', 'answer' => 'We recommend having basic programming knowledge, but the course starts from foundational concepts.'],
                    ['question' => 'Do we learn PHP or Python?', 'answer' => 'This cohort focuses heavily on the JavaScript/TypeScript ecosystem using Node.js.'],
                    ['question' => 'Will I build a portfolio?', 'answer' => 'Yes, you will complete three major backend projects tailored for production use.'],
                    ['question' => 'Why Node.js for backend?', 'answer' => 'Node.js allows for high performance, non-blocking I/O and lets you use a single language (JS/TS) across the stack.'],
                    ['question' => 'Is TypeScript included?', 'answer' => 'Yes, we transition from JavaScript to TypeScript in the second half of the track.'],
                ],
                'prerequisites' => 'Basic understanding of programming logic and JavaScript fundamentals.',
            ],
            [
                'slug' => 'frontend-development',
                'title' => 'Frontend Development',
                'category' => 'engineering',
                'description' => 'Build pixel-perfect, accessible, and performant user interfaces using React, TypeScript, and Tailwind CSS. You will cover state management, performance optimisation, and testing — finishing with a portfolio of production-ready projects that demonstrate your craft to employers.',
                'duration_weeks' => 10,
                'format' => 'cohort',
                'price_ngn' => 140000,
                'price_usd' => 95,
                'scholarship_price_ngn' => 14000,
                'is_published' => true,
                'is_featured' => false,
                'tools_and_technologies' => [
                    ['name' => 'React', 'logo_url' => '/logos/react.svg'],
                    ['name' => 'TypeScript', 'logo_url' => '/logos/typescript.svg'],
                    ['name' => 'Tailwind CSS', 'logo_url' => '/logos/tailwindcss.svg'],
                    ['name' => 'Next.js', 'logo_url' => '/logos/nextjs.svg'],
                    ['name' => 'Redux', 'logo_url' => '/logos/redux.svg'],
                    ['name' => 'Figma', 'logo_url' => '/logos/figma.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Frontend Developer', 'nigeria_ngn' => '₦4M - ₦8.5M', 'us_usd' => '$85,000 - $135,000', 'global_usd' => '$118,000'],
                    ['role' => 'React Developer', 'nigeria_ngn' => '₦4.5M - ₦9M', 'us_usd' => '$90,000 - $140,000', 'global_usd' => '$125,000'],
                ],
                'outcomes' => [
                    'Translate complex Figma designs into responsive, accessible code.',
                    'Master React 18 and the latest patterns (React Server Components).',
                    'Write type-safe frontend applications with TypeScript.',
                    'Implement complex state management with Redux Toolkit and React Query.',
                    'Build high-performance landing pages using Next.js.',
                    'Optimise Web Vitals for superior user experience and SEO.',
                    'Author unit and E2E tests for robust frontend stability.',
                ],
                'curriculum' => [
                    ['week' => 1, 'title' => 'Beyond CMS: Modern HTML/CSS', 'topics' => ['Advanced CSS Architecture', 'Tailwind Utility-First Approach', 'Accessibility (A11y) Standards']],
                    ['week' => 2, 'title' => 'React Foundations', 'topics' => ['JSX & Components', 'Props & State Management', 'Event Handling', 'Lists & Keys']],
                    ['week' => 3, 'title' => 'React Hooks Deep Dive', 'topics' => ['useState & useEffect', 'useRef & useMemo', 'useCallback', 'Custom Hooks Patterns']],
                    ['week' => 4, 'title' => 'TypeScript for Frontend', 'topics' => ['Typing Components', 'Interfaces & Types', 'Generics in React', 'API Responses']],
                    ['week' => 5, 'title' => 'Asynchronous React', 'topics' => ['React Query for Data Fetching', 'Handling Loading & Errors', 'Optimistic Updates']],
                    ['week' => 6, 'title' => 'Global State Management', 'topics' => ['Context API vs Redux', 'Redux Toolkit Patterns', 'State Normalisation']],
                    ['week' => 7, 'title' => 'Routing & Navigation', 'topics' => ['React Router 6', 'Protective Routes', 'Dynamic Parameters', 'Breadcrumbs']],
                    ['week' => 8, 'title' => 'Next.js & Server Side', 'topics' => ['App Router', 'Static vs Dynamic Generation', 'API Routes in Next.js']],
                    ['week' => 9, 'title' => 'Testing & Animation', 'topics' => ['Testing Library Foundations', 'Framer Motion for Interactions', 'Micro-animations']],
                    ['week' => 10, 'title' => 'Performance & Portfolio', 'topics' => ['Code Splitting', 'Lazy Loading', 'Bundle Analysis', 'Final Project Polish']],
                ],
                'about_mdx' => "The frontend is where users meet your product. This programme focuses on the craft of building **stunning, accessible, and high-performance** web interfaces.\n\nWe don't just teach you to build components; we teach you how to build **professional-grade design systems** using React, TypeScript, and Tailwind CSS. You'll master the logic of modern state management and the performance optimisations required for production-level apps.\n\nBy graduation, you will have a portfolio that doesn't just look good—it stands up to the technical scrutiny of senior engineering leads.",
                'faqs' => [
                    ['question' => 'Do I need design skills?', 'answer' => 'No design skills are required, but you will learn how to implement existing designs from Figma.'],
                    ['question' => 'Is TypeScript hard for beginners?', 'answer' => 'We introduce TypeScript gradually, making it very accessible.'],
                    ['question' => 'What happens if I miss a live class?', 'answer' => 'All live classes are recorded and available on your dashboard within 24 hours.'],
                    ['question' => 'Why React and not Vue or Angular?', 'answer' => 'React has the largest job market and ecosystem globally, specifically in the African startup scene.'],
                    ['question' => 'Do we learn Next.js?', 'answer' => 'Yes, Next.js is a core part of the track for building production-ready applications.'],
                ],
                'prerequisites' => 'Basic computer literacy. No prior coding experience necessary, though familiarity with HTML/CSS helps.',
            ],
            [
                'slug' => 'devops-engineering',
                'title' => 'DevOps Engineering',
                'category' => 'engineering',
                'description' => 'Learn the tools and practices that keep modern software running reliably at scale. This programme covers Linux systems, Docker, Kubernetes, CI/CD pipelines, Terraform, AWS/GCP, and site reliability engineering. Graduates consistently land roles paying ₦7M–₦13M annually.',
                'duration_weeks' => 14,
                'format' => 'cohort',
                'price_ngn' => 160000,
                'price_usd' => 110,
                'scholarship_price_ngn' => 16000,
                'is_published' => true,
                'is_featured' => false,
                'tools_and_technologies' => [
                    ['name' => 'Docker', 'logo_url' => '/logos/docker.svg'],
                    ['name' => 'Kubernetes', 'logo_url' => '/logos/kubernetes.svg'],
                    ['name' => 'AWS', 'logo_url' => '/logos/aws.svg'],
                    ['name' => 'Terraform', 'logo_url' => '/logos/terraform.svg'],
                    ['name' => 'GitHub Actions', 'logo_url' => '/logos/github-actions.svg'],
                    ['name' => 'Linux', 'logo_url' => '/logos/linux.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'DevOps Engineer', 'nigeria_ngn' => '₦7M - ₦13M', 'us_usd' => '$100,000 - $150,000', 'global_usd' => '$140,000'],
                    ['role' => 'Site Reliability Engineer', 'nigeria_ngn' => '₦8M - ₦15M', 'us_usd' => '$110,000 - $160,000', 'global_usd' => '$145,000'],
                ],
                'outcomes' => [
                    'Master Linux system administration and Bash scripting.',
                    'Containerise and orchestrate applications with Docker and Kubernetes.',
                    'Implement Infrastructure as Code (IaC) using Terraform.',
                    'Design and automate robust CI/CD pipelines with GitHub Actions.',
                    'Manage scalable cloud infrastructure on AWS and GCP.',
                    'Deploy and maintain monitoring stacks (Prometheus, Grafana).',
                    'Implement Site Reliability Engineering (SRE) best practices.',
                ],
                'curriculum' => [
                    ['week' => 1, 'title' => 'Linux Foundations', 'topics' => ['Bash Scripting', 'User Management', 'File Permissions', 'Process Management']],
                    ['week' => 2, 'title' => 'Networking for DevOps', 'topics' => ['TCP/IP Foundations', 'DNS & DHCP', 'SSH & Firewalls', 'Load Balancers']],
                    ['week' => 3, 'title' => 'Source Control & GitOps', 'topics' => ['Advanced Git Patterns', 'Conventional Commits', 'Semantic Versioning']],
                    ['week' => 4, 'title' => 'Docker Deep Dive', 'topics' => ['Building Images', 'Multi-stage Builds', 'Docker Networking', 'Volumes']],
                    ['week' => 5, 'title' => 'CI/CD Pipelines', 'topics' => ['GitHub Actions', 'Build Automation', 'Automated Testing in Pipeline', 'Secrets Management']],
                    ['week' => 6, 'title' => 'Cloud Provider: AWS', 'topics' => ['EC2 & VPC', 'S3 & IAM', 'Route53 & CloudFront', 'Lambda Basics']],
                    ['week' => 7, 'title' => 'Infrastructure as Code', 'topics' => ['Terraform Providers', 'TF State Management', 'Terraform Modules', 'Variables']],
                    ['week' => 8, 'title' => 'Kubernetes Foundations', 'topics' => ['Pod Lifecycle', 'Services & Ingress', 'ConfigMaps & Secrets', 'Deployments']],
                    ['week' => 9, 'title' => 'Kubernetes Operations', 'topics' => ['Helm Charts', 'Persistent Volumes', 'Horizontal Pod Autoscaling (HPA)']],
                    ['week' => 10, 'title' => 'Configuration Management', 'topics' => ['Ansible Playbooks', 'Roles & Inventories', 'Agentless Automation']],
                    ['week' => 11, 'title' => 'Monitoring & Logging', 'topics' => ['Prometheus & Grafana', 'ELK Stack', 'Tracing with Jaeger']],
                    ['week' => 12, 'title' => 'Site Reliability Engineering', 'topics' => ['SLIs & SLOs', 'Error Budgets', 'Incident Response', 'Post-mortems']],
                    ['week' => 13, 'title' => 'Security (DevSecOps)', 'topics' => ['Container Scanning', 'SAST & DAST', 'Cloud Security Audits']],
                    ['week' => 14, 'title' => 'Final Capstone', 'topics' => ['Architecture Design', 'Full Pipeline Build', 'Mock Infrastructure Review']],
                ],
                'about_mdx' => "DevOps is the glue that binds development and operations together. This programme prepares you for the **highest-paid technical roles** in the ecosystem by teaching you how to build automated, stable, and scalable infrastructure.\n\nYou'll master the **trinity of modern DevOps**: Docker for containerisation, Kubernetes for orchestration, and Terraform for infrastructure as code. We don't just teach tools; we teach the **automation-first mindset** that defines successful SRE and DevOps teams.\n\nIf you want to be the engineer who builds the systems that allow others to ship code safely, this is the track for you.",
                'faqs' => [
                    ['question' => 'Is DevOps for beginners?', 'answer' => 'DevOps is best suited for individuals with some background in software development or IT administration.'],
                    ['question' => 'Will I need to pay for AWS?', 'answer' => 'We use free tier resources extensively, but expect to spend about $10-$20 on real-world infrastructure practice.'],
                    ['question' => 'Are certifications included?', 'answer' => 'The curriculum prepares you for AWS certifications, but the exam fees are not included.'],
                    ['question' => 'Is there a focus on Python?', 'answer' => 'We cover Python for scripting and automation as it is a core DevOps skill.'],
                    ['question' => 'Can I land a job without prior dev experience?', 'answer' => 'It is harder but possible. We recommend this track for those with prior tech exposure.'],
                ],
                'prerequisites' => 'Basic understanding of software development lifecycle, web servers, and fundamental networking concepts.',
            ],

            // Data & Emerging Technologies
            [
                'slug' => 'data-science',
                'title' => 'Data Science',
                'category' => 'data',
                'description' => 'Master the most in-demand skill of the 21st century. This 16-week intensive track covers Python, statistics, machine learning, deep learning (TensorFlow), and data engineering. You will work on real-world African datasets and graduate with a portfolio of predictive models ready for production.',
                'duration_weeks' => 16,
                'format' => 'cohort',
                'price_ngn' => 160000,
                'price_usd' => 110,
                'scholarship_price_ngn' => 16000,
                'is_published' => true,
                'is_featured' => true,
                'tools_and_technologies' => [
                    ['name' => 'Python', 'logo_url' => '/logos/python.svg'],
                    ['name' => 'TensorFlow', 'logo_url' => '/logos/tensorflow.svg'],
                    ['name' => 'Pandas', 'logo_url' => '/logos/pandas.svg'],
                    ['name' => 'Scikit-learn', 'logo_url' => '/logos/scikitlearn.svg'],
                    ['name' => 'SQL', 'logo_url' => '/logos/sql.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Data Scientist', 'nigeria_ngn' => '₦6M - ₦12M', 'us_usd' => '$100,000 - $165,000', 'global_usd' => '$145,000'],
                    ['role' => 'ML Engineer', 'nigeria_ngn' => '₦7M - ₦14M', 'us_usd' => '$110,000 - $175,000', 'global_usd' => '$155,000'],
                ],
                'outcomes' => [
                    'Master Python for data science and machine learning.',
                    'Design and implement end-to-end machine learning pipelines.',
                    'Build and deploy deep learning models using TensorFlow.',
                    'Extract complex insights from large-scale stayistical datasets.',
                    'Master SQL for data extraction and manipulation.',
                    'Communicate technical insights to non-technical stakeholders.',
                    'Apply data science techniques to real-world African business problems.',
                ],
                'curriculum' => [
                    ['week' => 1, 'title' => 'Python for Data Science', 'topics' => ['Python Basics', 'Control Flow', 'Functions', 'Data Structures']],
                    ['week' => 2, 'title' => 'Mathematical Foundations', 'topics' => ['Linear Algebra', 'Calculus', 'Probability theory', 'Distributions']],
                    ['week' => 3, 'title' => 'Data Manipulation', 'topics' => ['Pandas Mastery', 'NumPy Operations', 'Cleaning Messy Data', 'Data Wrangling']],
                    ['week' => 4, 'title' => 'Exploratory Data Analysis', 'topics' => ['Matplotlib Foundations', 'Seaborn Visualisations', 'Feature Engineering']],
                    ['week' => 5, 'title' => 'SQL for Data Science', 'topics' => ['Joins & Subqueries', 'Window Functions', 'Query Optimisation', 'Database Design']],
                    ['week' => 6, 'title' => 'Classical Machine Learning', 'topics' => ['Linear Regression', 'Logistic Regression', 'Decision Trees', 'Random Forests']],
                    ['week' => 7, 'title' => 'Advanced ML Algorithms', 'topics' => ['Support Vector Machines', 'XGBoost', 'K-Means Clustering', 'PCA']],
                    ['week' => 8, 'title' => 'Model Evaluation', 'topics' => ['Cross-validation', 'Confusion Matrices', 'Hyperparameter Tuning', 'Bias & Variance']],
                    ['week' => 9, 'title' => 'Deep Learning Foundations', 'topics' => ['Neural Networks Basics', 'Activation Functions', 'Backpropagation', 'TensorFlow Basics']],
                    ['week' => 10, 'title' => 'Computer Vision', 'topics' => ['Convolutional Neural Networks (CNN)', 'Image Recognition', 'Transfer Learning']],
                    ['week' => 11, 'title' => 'Natural Language Processing', 'topics' => ['Sentiment Analysis', 'Text Preprocessing', 'Word Embeddings', 'RNNs']],
                    ['week' => 12, 'title' => 'Data Science in Production', 'topics' => ['API Deployment (FastAPI)', 'Docker for Data Science', 'Monitoring Model Drift']],
                    ['week' => 13, 'title' => 'Real-world Capstone I', 'topics' => ['Project Scoping', 'Data Collection', 'Baseline Modelling']],
                    ['week' => 14, 'title' => 'Real-world Capstone II', 'topics' => ['Advanced Modelling', 'Result Visualisation', 'Final Presentation']],
                    ['week' => 15, 'title' => 'Career Preparation', 'topics' => ['Kaggle mastery', 'Building a Portfolio', 'Tech Interview Practice']],
                    ['week' => 16, 'title' => 'Final Demo Day', 'topics' => ['Showcasing Projects', 'Networking with Industry Partners']],
                ],
                'about_mdx' => "Move from data to decisions with our comprehensive **16-week Data Science track**. This programme is built for thinkers who want to solve complex problems using the power of **Python, Machine Learning, and Big Data**.\n\nYou won't just learn to code; you'll learn to think like a scientist. We cover the entire lifecycle of a data project—from initial scraping and cleaning to building predictive models and deploying them to production. \n\nA key highlight of this track is our partnership with local industry players, ensuring you work on **genuine African datasets** that reflect the unique challenges of the continent's data landscape.",
                'faqs' => [
                    ['question' => 'Do I need a maths background?', 'answer' => 'High school level mathematics is required. We will teach you the specific statistics needed for data science.'],
                    ['question' => 'What is the difference between Data Science and Analytics?', 'answer' => 'Data Science involves more predictive modelling and machine learning, while Analytics focuses on descriptive insights and business intelligence.'],
                    ['question' => 'Will I learn Python from scratch?', 'answer' => 'Yes, the first month focuses heavily on foundational Python programming.'],
                    ['question' => 'Do I need a high-end laptop?', 'answer' => 'A laptop with 8GB RAM is minimum, but we use cloud-based tools like Google Colab for heavy computations.'],
                    ['question' => 'Are there job opportunities in Africa?', 'answer' => 'Yes, fintech and logistics companies in Africa are hiring data scientists at record rates.'],
                    ['question' => 'Is this a full-time course?', 'answer' => 'It is part-time but intensive, requiring roughly 20 hours of commitment per week.'],
                ],
                'prerequisites' => 'Basic mathematics (statistics/algebra) foundation. No prior coding experience required.',
            ],
            [
                'slug' => 'data-analytics',
                'title' => 'Data Analytics',
                'category' => 'data',
                'description' => 'Turn raw data into actionable business intelligence. Starting from Excel and SQL, you will progress through Power BI, Python (pandas, NumPy), and AI-augmented analytics using ChatGPT and Copilot. The 3-month programme ends with a real-world dataset capstone you can present to employers.',
                'duration_weeks' => 12,
                'format' => 'cohort',
                'price_ngn' => 130000,
                'price_usd' => 88,
                'scholarship_price_ngn' => 13000,
                'is_published' => true,
                'is_featured' => true,
                'tools_and_technologies' => [
                    ['name' => 'SQL', 'logo_url' => '/logos/sql.svg'],
                    ['name' => 'Excel', 'logo_url' => '/logos/excel.svg'],
                    ['name' => 'Power BI', 'logo_url' => '/logos/powerbi.svg'],
                    ['name' => 'Python', 'logo_url' => '/logos/python.svg'],
                    ['name' => 'Tableau', 'logo_url' => '/logos/tableau.svg'],
                    ['name' => 'Copilot', 'logo_url' => '/logos/github-copilot.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Data Analyst', 'nigeria_ngn' => '₦4.8M - ₦8M', 'us_usd' => '$80,000 - $115,000', 'global_usd' => '$121,000'],
                    ['role' => 'Business Intelligence Analyst', 'nigeria_ngn' => '₦5M - ₦9M', 'us_usd' => '$85,000 - $120,000', 'global_usd' => '$125,000'],
                ],
                'outcomes' => [
                    'Master advanced data manipulation in Microsoft Excel.',
                    'Write complex SQL queries for data extraction and business reporting.',
                    'Build interactive, production-ready dashboards in Power BI and Tableau.',
                    'Use Python for professional-grade data cleaning and analysis.',
                    'Leverage AI tools for augmented analytical workflows.',
                    'Design and present compelling data stories to executives.',
                    'Conduct thorough exploratory data analysis on real business sets.',
                ],
                'curriculum' => [
                    ['week' => 1, 'title' => 'Advanced Excel Foundations', 'topics' => ['Pivots & Lookups', 'Power Query Basics', 'Data Cleaning Techniques']],
                    ['week' => 2, 'title' => 'Excel for Analytics', 'topics' => ['Statistical Analysis', 'Forecasting Patterns', 'Financial Modelling Basics']],
                    ['week' => 3, 'title' => 'Relational Data & SQL I', 'topics' => ['Table Relationships', 'SQL Syntax Foundations', 'Filtering & Sorting Data']],
                    ['week' => 4, 'title' => 'Advanced SQL II', 'topics' => ['Subqueries & CTEs', 'Window Functions', 'Performance Tuning Queries']],
                    ['week' => 5, 'title' => 'Power BI Foundations', 'topics' => ['DAX Language Bases', 'Data Modelling', 'Building First Dashboards']],
                    ['week' => 6, 'title' => 'Advanced Visualisation', 'topics' => ['Dashboard UX/UI Design', 'Storytelling with Highcharts', 'Interaction Patterns']],
                    ['week' => 7, 'title' => 'Tableau Essentials', 'topics' => ['Calculated Fields', 'Parameters', 'Mapping Data', 'Publishing Reports']],
                    ['week' => 8, 'title' => 'Python for Analysts I', 'topics' => ['Pandas Fundamentals', 'Series vs DataFrames', 'Cleaning Data with Python']],
                    ['week' => 9, 'title' => 'Python for Analysts II', 'topics' => ['Vectorised Operations', 'Matplotlib for Analysts', 'Statistical Viz']],
                    ['week' => 10, 'title' => 'AI Augmentation', 'topics' => ['ChatGPT for SQL Generation', 'Copilot for Python Scripting', 'Automating Cleanup']],
                    ['week' => 11, 'title' => 'Strategy & Communication', 'topics' => ['Stakeholder Management', 'Drafting Exec Summaries', 'Data Narrative Prep']],
                    ['week' => 12, 'title' => 'Capstone Delivery', 'topics' => ['Data Cleaning', 'Insight Discovery', 'Final Dashboard Build', 'Presentation Viva']],
                ],
                'about_mdx' => "In the modern economy, data is the new oil, and analysts are the refiners. This **12-week track** transforms you into a highly sought-after professional capable of turning raw spreadsheets into **strategic business gold**.\n\nWe start with the bedrock of industry—**Excel and SQL**—before moving into modern visualisation tools like **Power BI and Tableau**. You'll also learn the cutting-edge of the field: using **AI-augmented tools** to speed up your analysis by 10x.\n\nWhether you're looking to pivot your career or level up in your current role, this track provides the technical skills and the business acumen required to lead data-driven organisations.",
                'faqs' => [
                    ['question' => 'Is this a coding course?', 'answer' => 'It involves some coding (Python and SQL), but is much lighter on programming than the software engineering tracks.'],
                    ['question' => 'Can I do this on a Mac?', 'answer' => 'Yes, though Power BI is Windows-only, so Mac users will need to use a virtual machine or focus on Tableau.'],
                    ['question' => 'Will I work on real projects?', 'answer' => 'Yes, the capstone project uses genuine datasets from industry partners.'],
                    ['question' => 'Do I need prior data experience?', 'answer' => 'No, we start from the absolute basics of spreadsheets.'],
                    ['question' => 'Is Power BI better than Tableau?', 'answer' => 'Both are industry leaders. We teach both to ensure you are adaptable to any company ecosystem.'],
                    ['question' => 'How much math is involved?', 'answer' => 'Basic arithmetic and high-school level statistics are sufficient.'],
                ],
                'prerequisites' => 'Comfort with basic computer operations and spreadsheet software (like Excel or Google Sheets).',
            ],
            [
                'slug' => 'ai-automation',
                'title' => 'AI & Automation',
                'category' => 'data',
                'description' => 'Build intelligent systems and automate repetitive workflows using Python, OpenAI APIs, LangChain, n8n, and Zapier. You will ship three working AI-powered tools during the programme, giving you a portfolio that stands out in a rapidly evolving job market.',
                'duration_weeks' => 12,
                'format' => 'cohort',
                'price_ngn' => 150000,
                'price_usd' => 100,
                'scholarship_price_ngn' => 15000,
                'is_published' => true,
                'is_featured' => false,
                'tools_and_technologies' => [
                    ['name' => 'Python', 'logo_url' => '/logos/python.svg'],
                    ['name' => 'OpenAI', 'logo_url' => '/logos/openai.svg'],
                    ['name' => 'LangChain', 'logo_url' => '/logos/langchain.svg'],
                    ['name' => 'Zapier', 'logo_url' => '/logos/zapier.svg'],
                    ['name' => 'Make', 'logo_url' => '/logos/make.svg'],
                    ['name' => 'n8n', 'logo_url' => '/logos/n8n.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'AI / Automation Engineer', 'nigeria_ngn' => '₦7M - ₦14M', 'us_usd' => '$110,000 - $175,000', 'global_usd' => '$155,000'],
                    ['role' => 'Workflow Consultant', 'nigeria_ngn' => '₦6M - ₦12M', 'us_usd' => '$90,000 - $140,000', 'global_usd' => '$130,000'],
                ],
                'outcomes' => [
                    'Architect and deploy end-to-end AI automation workflows.',
                    'Master Large Language Model (LLM) integration using OpenAI and Anthropic.',
                    'Build advanced AI agents with LangChain and LlamaIndex.',
                    'Automate business processes using n8n, Make, and Zapier.',
                    'Design high-converting prompt engineering systems.',
                    'Manage vector databases (Pinecone, Weaviate) for RAG applications.',
                    'Build custom AI tools with Python for specific industry use cases.',
                ],
                'curriculum' => [
                    ['week' => 1, 'title' => 'Python for Automation', 'topics' => ['Scripting Basics', 'Automating File Systems', 'Web Scraping Foundations']],
                    ['week' => 2, 'title' => 'API Mastery', 'topics' => ['RESTful Communication', 'Handling Webhooks', 'Authentication Headers']],
                    ['week' => 3, 'title' => 'No-Code Foundations', 'topics' => ['Zapier/Make Workflows', 'Error Handling', 'Multi-step Automations']],
                    ['week' => 4, 'title' => 'n8n for Advanced Workflows', 'topics' => ['Self-hosting n8n', 'Node Customisation', 'Workflow Optimization']],
                    ['week' => 5, 'title' => 'Intro to LLMs', 'topics' => ['Tokenisation Bases', 'Prompt Engineering Patterns', 'OpenAI API Mastery']],
                    ['week' => 6, 'title' => 'LangChain Foundations', 'topics' => ['Chains & Chains', 'Memory Patterns', 'Building First AI Chatbot']],
                    ['week' => 7, 'title' => 'RAG Architectures', 'topics' => ['Vector Embeddings', 'Document Ingestion', 'Retrieval Strategies']],
                    ['week' => 8, 'title' => 'AI Agents', 'topics' => ['Tool Calling', 'Planning Patterns', 'Autononmous Agents Development']],
                    ['week' => 9, 'title' => 'Voice & Vision AI', 'topics' => ['Whisper Integration', 'Image Generation APIs', 'Multimodal Workflows']],
                    ['week' => 10, 'title' => 'Deployment & Scaling', 'topics' => ['Cloud Deployment', 'Security in Automations', 'Monitoring AI Costs']],
                    ['week' => 11, 'title' => 'Business Consultation', 'topics' => ['Scoping Automation Projects', 'ROI Calculation', 'Selling to Clients']],
                    ['week' => 12, 'title' => 'Final Capstone Project', 'topics' => ['Full Build of an AI Product', 'Testing & Optimisation', 'Demo Session']],
                ],
                'about_mdx' => "The future of work is not just about doing tasks; it's about building the systems that do them for you. This **12-week track** is at the absolute cutting edge of the tech sector.\n\nYou will learn to wield the power of **Generative AI** alongside robust **automation frameworks** like n8n and Zapier. We'll show you how to build AI agents that can read emails, process documents, and communicate with external APIs—all while you sleep.\n\nThis track is designed for the high-frequency professional who wants to lead the AI revolution within their organisation or start a lucrative consulting practice.",
                'faqs' => [
                    ['question' => 'Do I need to be a software engineer first?', 'answer' => 'No, but you will learn basic Python. The focus is on integration rather than building apps from scratch.'],
                    ['question' => 'Are API costs included?', 'answer' => 'You will need to cover your own OpenAI/Anthropic API costs, which typically run $5-$10 per month during the course.'],
                    ['question' => 'Is this a future-proof skill?', 'answer' => 'Absolutely. Automation and AI implementation are currently the fastest-growing sectors in tech.'],
                    ['question' => 'Will we build real AI agents?', 'answer' => 'Yes, you will build and deploy three distinct AI agents during the cohort.'],
                    ['question' => 'Do we use LangChain?', 'answer' => 'Yes, LangChain is a core part of the advanced modules.'],
                    ['question' => 'What if I have zero coding experience?', 'answer' => 'We have a "Fast Track" Python module in week 1 to get you up to speed.'],
                ],
                'prerequisites' => 'A keen analytical mind and basic understanding of how web services interact.',
            ],

            // Design & Creativity
            [
                'slug' => 'product-design',
                'title' => 'Product Design',
                'category' => 'design',
                'description' => 'Learn the full spectrum of modern product design. From user research and journey mapping to high-fidelity prototyping in Figma and usability testing. You will learn to think like a product designer and build solutions that are as functional as they are beautiful. Graduates build three comprehensive case studies during the programme.',
                'duration_weeks' => 12,
                'format' => 'cohort',
                'price_ngn' => 130000,
                'price_usd' => 88,
                'scholarship_price_ngn' => 13000,
                'is_published' => true,
                'is_featured' => true,
                'tools_and_technologies' => [
                    ['name' => 'Figma', 'logo_url' => '/logos/figma.svg'],
                    ['name' => 'FigJam', 'logo_url' => '/logos/figjam.svg'],
                    ['name' => 'Maze', 'logo_url' => '/logos/maze.svg'],
                    ['name' => 'Miro', 'logo_url' => '/logos/miro.svg'],
                    ['name' => 'Webflow', 'logo_url' => '/logos/webflow.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Product Designer', 'nigeria_ngn' => '₦5M - ₦10M', 'us_usd' => '$90,000 - $145,000', 'global_usd' => '$128,000'],
                    ['role' => 'UX Researcher', 'nigeria_ngn' => '₦4M - ₦7.5M', 'us_usd' => '$80,000 - $120,000', 'global_usd' => '$115,000'],
                ],
                'outcomes' => [
                    'Master professional-grade UI/UX design workflows in Figma.',
                    'Conduct thorough user research and translate findings into insights.',
                    'Create high-fidelity interactive prototypes for stakeholder testing.',
                    'Design and document cohesive, scalable design systems.',
                    'Apply psychological principles of design to improve user retention.',
                    'Demonstrate mastery of typography, color theory, and layout.',
                    'Build a professional portfolio with three comprehensive case studies.',
                ],
                'curriculum' => [
                    ['week' => 1, 'title' => 'Design Foundations', 'topics' => ['Design Thinking Mindset', 'History of UI/UX', 'The Product Designer Role']],
                    ['week' => 2, 'title' => 'User Research Mastery', 'topics' => ['Quantitative vs Qualitative', 'User Interviews', 'Survey Design', 'Empathy Maps']],
                    ['week' => 3, 'title' => 'Ideation & Strategy', 'topics' => ['Problem Definition', 'User Personas', 'Information Architecture', 'User Flows']],
                    ['week' => 4, 'title' => 'Figma Foundations', 'topics' => ['Auto Layout Mastery', 'Components & Variants', 'Styles & Variables']],
                    ['week' => 5, 'title' => 'Wireframing & Lo-Fi', 'topics' => ['Sketching Techniques', 'Low-fidelity Prototyping', 'Content Strategy']],
                    ['week' => 6, 'title' => 'Visual Design Principles', 'topics' => ['Typography Systems', 'Inclusive Colour Theory', 'Grid Systems & Spacing']],
                    ['week' => 7, 'title' => 'High-Fidelity UI', 'topics' => ['Advanced Figma Prototyping', 'Micro-interactions', 'Iconography Bases']],
                    ['week' => 8, 'title' => 'Design Systems', 'topics' => ['Atomic Design Principles', 'Documentation in ZeroHeight', 'Design-to-Code Handoff']],
                    ['week' => 9, 'title' => 'Usability Testing', 'topics' => ['Maze for Testing', 'A/B Testing Foundations', 'Iterating on Feedback']],
                    ['week' => 10, 'title' => 'Accessibility (A11y)', 'topics' => ['WCAG Guidelines', 'Screen Reader Testing', 'Inclusive Copywriting']],
                    ['week' => 11, 'title' => 'Portfolio Strategy', 'topics' => ['Case Study Storytelling', 'Building in Framer/Webflow', 'Personal Branding']],
                    ['week' => 12, 'title' => 'Final Presentation', 'topics' => ['The Portfolio Review', 'Interview Prep for Designers', 'Final Project Demo']],
                ],
                'about_mdx' => "Digital products are successful because of how they work, not just how they look. This **12-week track** transforms you into a holistic **Product Designer** capable of leading the entire design lifecycle.\n\nYou'll learn more than just Figma shortcuts. You'll master **user research**, complex **prototyping**, and the strategic thinking required to build products that solve genuine human problems. \n\nBy the end of the programme, you'll have three deep-dive case studies that demonstrate your ability to think, research, and execute at a professional level, giving you the edge in a competitive global job market.",
                'faqs' => [
                    ['question' => 'Do I need drawing skills?', 'answer' => 'Not at all. Product design is about problem-solving and systems thinking, not illustration.'],
                    ['question' => 'Do we learn to code?', 'answer' => 'No. We teach you how to hand off designs to developers, but you will not be writing production code.'],
                    ['question' => 'Why three case studies?', 'answer' => 'Industry standard portfolios require at least three comprehensive case studies to demonstrate consistency.'],
                    ['question' => 'What is the difference between UI and UX?', 'answer' => 'UX (User Experience) is how a user feels and interacts, while UI (User Interface) is the specific visual design they see.'],
                    ['question' => 'Do I need a Mac?', 'answer' => 'No, Figma works perfectly in any browser on Windows or Linux.'],
                    ['question' => 'Is this only for web apps?', 'answer' => 'We cover both web and mobile app design patterns.'],
                ],
                'prerequisites' => 'Empathy for users and strong problem-solving skills.',
            ],
            [
                'slug' => 'graphics-design',
                'title' => 'Graphics Design',
                'category' => 'design',
                'description' => 'Build a professional graphics design practice using Adobe Photoshop, Illustrator, and InDesign. You will cover brand identity design, typography, print and digital layouts, and client communication. Wenza graduates regularly land roles at agencies and go on to build successful freelance practices.',
                'duration_weeks' => 10,
                'format' => 'cohort',
                'price_ngn' => 110000,
                'price_usd' => 75,
                'scholarship_price_ngn' => 11000,
                'is_published' => true,
                'is_featured' => false,
                'tools_and_technologies' => [
                    ['name' => 'Photoshop', 'logo_url' => '/logos/photoshop.svg'],
                    ['name' => 'Illustrator', 'logo_url' => '/logos/illustrator.svg'],
                    ['name' => 'InDesign', 'logo_url' => '/logos/indesign.svg'],
                    ['name' => 'CorelDRAW', 'logo_url' => '/logos/coreldraw.svg'],
                    ['name' => 'Canva', 'logo_url' => '/logos/canva.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Graphics Designer', 'nigeria_ngn' => '₦3M - ₦6.5M', 'us_usd' => '$55,000 - $90,000', 'global_usd' => '$68,000'],
                    ['role' => 'Brand Identity Designer', 'nigeria_ngn' => '₦4M - ₦7M', 'us_usd' => '$60,000 - $95,000', 'global_usd' => '$75,000'],
                ],
                'outcomes' => [
                    'Master professional-level photo manipulation in Adobe Photoshop.',
                    'Design scalable vector graphics and logos using Adobe Illustrator.',
                    'Create complex multi-page layouts in Adobe InDesign.',
                    'Produce comprehensive brand identity systems for clients.',
                    'Design professional marketing collateral for print and digital.',
                    'Master the business of design including pricing and client management.',
                    'Curate a professional-grade creative portfolio.',
                ],
                'curriculum' => [
                    ['week' => 1, 'title' => 'Photoshop Foundations', 'topics' => ['Selection Tools', 'Layers & Masks', 'Retouching Basics', 'Colour Correction']],
                    ['week' => 2, 'title' => 'Advanced Photoshop', 'topics' => ['Smart Objects', 'Complex Compositing', 'Text Effects', 'Exporting for Web']],
                    ['week' => 3, 'title' => 'Illustrator Foundations', 'topics' => ['Pen Tool Mastery', 'Shapes & Pathfinders', 'Vectors vs Rasters']],
                    ['week' => 4, 'title' => 'Logo & Identity Design', 'topics' => ['Iconography', 'Typography for Logos', 'Colour Systems in Branding']],
                    ['week' => 5, 'title' => 'Brand Expression', 'topics' => ['Stationery Design', 'Social Media Templates', 'Visual Consistency']],
                    ['week' => 6, 'title' => 'InDesign & Layout', 'topics' => ['Master Pages', 'Character & Paragraph Styles', 'Working with Large Text']],
                    ['week' => 7, 'title' => 'Print Production', 'topics' => ['Bleeds & Margins', 'CMYK vs RGB', 'Preparing Files for Print Vendors']],
                    ['week' => 8, 'title' => 'Digital Layouts', 'topics' => ['Presentation Design', 'Brochures for Screen', 'Interactive PDFs']],
                    ['week' => 9, 'title' => 'Freelance Mastery', 'topics' => ['Pricing your Work', 'Contract Basics', 'Finding Clients in Nigeria']],
                    ['week' => 10, 'title' => 'Portfolio & Career', 'topics' => ['Curating Projects', 'Building an Online Portfolio', 'Final Project Review']],
                ],
                'about_mdx' => "Graphic design is the visual language of business. This **10-week programme** is designed to take you from a curious beginner to a **professional visual communicator** using the undisputed industry standard: Adobe Creative Cloud.\n\nYou'll master the 'Big Three'—**Photoshop, Illustrator, and InDesign**—learning exactly when and how to use each for maximum impact. More than just tools, we teach the **art of branding**, typography, and layout that separates the amateurs from the professionals.\n\nWhether you want to work at an agency, join a corporate marketing team, or build a thriving freelance business, this track gives you the technical and commercial foundation you need to succeed.",
                'faqs' => [
                    ['question' => 'Do I get the Adobe software?', 'answer' => 'You must purchase your own Adobe Creative Cloud subscription.'],
                    ['question' => 'Can I use Canva instead?', 'answer' => 'We will touch on Canva for quick workflows, but the core curriculum is built on professional Adobe tools.'],
                    ['question' => 'Is freelance covered?', 'answer' => 'Yes, a full module is dedicated to pricing, proposals, and client management for freelancers.'],
                    ['question' => 'Will I learn to design logos?', 'answer' => 'Yes, identity design is a core part of the Illustrator module.'],
                    ['question' => 'Do I need a powerful computer?', 'answer' => 'You need a computer that can run Adobe Photoshop and Illustrator reasonably well.'],
                    ['question' => 'What is CorelDRAW?', 'answer' => 'It is another popular layout tool we offer intro modules for, especially for the local print market.'],
                ],
                'prerequisites' => 'A computer capable of running Adobe CC software smoothly. No prior design experience required.',
            ],
            [
                'slug' => 'content-creation',
                'title' => 'Content Creation',
                'category' => 'design',
                'description' => 'Learn to create compelling content across video, social media, podcasting, and written formats. You will master the craft of storytelling, SEO writing, video editing (DaVinci Resolve, CapCut), and building an audience. The programme teaches you to monetise your skills through brand deals, consulting, and digital products.',
                'duration_weeks' => 8,
                'format' => 'cohort',
                'price_ngn' => 90000,
                'price_usd' => 60,
                'scholarship_price_ngn' => 9000,
                'is_published' => true,
                'is_featured' => false,
                'tools_and_technologies' => [
                    ['name' => 'CapCut', 'logo_url' => '/logos/capcut.svg'],
                    ['name' => 'DaVinci Resolve', 'logo_url' => '/logos/davinci.svg'],
                    ['name' => 'WordPress', 'logo_url' => '/logos/wordpress.svg'],
                    ['name' => 'Notion', 'logo_url' => '/logos/notion.svg'],
                    ['name' => 'Substack', 'logo_url' => '/logos/substack.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Content Creator', 'nigeria_ngn' => '₦2.5M - ₦6M', 'us_usd' => '$45,000 - $85,000', 'global_usd' => '$62,000'],
                    ['role' => 'Social Media Manager', 'nigeria_ngn' => '₦3M - ₦6.5M', 'us_usd' => '$50,000 - $85,000', 'global_usd' => '$65,000'],
                ],
                'outcomes' => [
                    'Script and produce high-retention video content for social platforms.',
                    'Master professional video editing in CapCut and DaVinci Resolve.',
                    'Build and grow a dedicated audience on social media organically.',
                    'Write SEO-optimised articles and compelling newsletters.',
                    'Launch and manage a professional podcast or YouTube channel.',
                    'Master monetisation strategies including brand deals and digital products.',
                    'Design a content strategy for brands and high-net-worth individuals.',
                ],
                'curriculum' => [
                    ['week' => 1, 'title' => 'The Art of Storytelling', 'topics' => ['Hook, Story, Offer Framework', 'Viral Content Patterns', 'Finding your Niche']],
                    ['week' => 2, 'title' => 'Professional Writing', 'topics' => ['SEO Article Writing', 'Email Copywriting', 'Scriptwriting for Video']],
                    ['week' => 3, 'title' => 'Short-form Video Mastery', 'topics' => ['TikTok/Reels Psychology', 'Shooting on Smartphone', 'Lighting & Audio']],
                    ['week' => 4, 'title' => 'Mobile Editing (CapCut)', 'topics' => ['Speed Ramping', 'Text & Overlays', 'Trend Analysis & Remixing']],
                    ['week' => 5, 'title' => 'Advanced Editing (DaVinci)', 'topics' => ['Timeline Management', 'Colour Grading', 'Sound Design Basics']],
                    ['week' => 6, 'title' => 'Social Strategy', 'topics' => ['Algorithm Secrets', 'Community Management', 'Cross-platform Syndication']],
                    ['week' => 7, 'title' => 'Monetisation & Branding', 'topics' => ['Brand Deals Mastery', 'Personal Branding', 'Selling Digital Products']],
                    ['week' => 8, 'title' => 'The Creator Economy', 'topics' => ['Workflow & Productivity', 'Managing Burnout', 'Final Project Review']],
                ],
                'about_mdx' => "Content is the currency of the digital age. This **8-week track** is a practical masterclass in the **craft and business of creation**. \n\nYou won't just learn to edit videos; you'll learn the **psychology of attention** that makes content go viral. We move from the simple, fast-paced world of **CapCut** to the high-end professional suite of **DaVinci Resolve**, ensuring you have the tools for any production level.\n\nCrucially, we teach you how to turn your creativity into a **business**. You'll graduate with a clear content strategy, a polished portfolio, and the knowledge required to monetise your audience or help brands reach theirs.",
                'faqs' => [
                    ['question' => 'Do I need an expensive camera?', 'answer' => 'No. A modern smartphone is all you need to start the video modules.'],
                    ['question' => 'Will my followers grow instantly?', 'answer' => 'Content creation requires consistency. We provide the strategy; you provide the reps.'],
                    ['question' => 'Is this only for influencers?', 'answer' => 'Not at all. Businesses desperately need skilled in-house creators for corporate channels.'],
                    ['question' => 'Do I need a Mac for DaVinci?', 'answer' => 'No, DaVinci Resolve runs on Windows and Mac, though you need a decent GPU.'],
                    ['question' => 'What platforms do we focus on?', 'answer' => 'Primarily TikTok, Instagram, YouTube, and Substack.'],
                    ['question' => 'Will I learn to use AI?', 'answer' => 'Yes, we use AI tools for scripting and thumbnail generation.'],
                ],
                'prerequisites' => 'A smartphone capable of shooting decent 1080p video, and a passion for storytelling.',
            ],

            // Management & Business
            [
                'slug' => 'product-management',
                'title' => 'Product Management',
                'category' => 'business',
                'description' => 'Learn what it takes to define, build, and launch great products. This 11-module programme covers market research, product vision, Agile methodology, user-centred design, data analytics, and stakeholder management. Wenza PM graduates earn ₦7M–₦12M annually at top Nigerian tech companies.',
                'duration_weeks' => 12,
                'format' => 'cohort',
                'price_ngn' => 150000,
                'price_usd' => 100,
                'scholarship_price_ngn' => 15000,
                'is_published' => true,
                'is_featured' => true,
                'tools_and_technologies' => [
                    ['name' => 'Jira', 'logo_url' => '/logos/jira.svg'],
                    ['name' => 'Linear', 'logo_url' => '/logos/linear.svg'],
                    ['name' => 'Mixpanel', 'logo_url' => '/logos/mixpanel.svg'],
                    ['name' => 'Amplitude', 'logo_url' => '/logos/amplitude.svg'],
                    ['name' => 'Figma', 'logo_url' => '/logos/figma.svg'],
                    ['name' => 'Notion', 'logo_url' => '/logos/notion.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Product Manager', 'nigeria_ngn' => '₦7M - ₦12M', 'us_usd' => '$105,000 - $155,000', 'global_usd' => null],
                    ['role' => 'Associate Product Manager', 'nigeria_ngn' => '₦5M - ₦8M', 'us_usd' => '$85,000 - $110,000', 'global_usd' => null],
                ],
                'outcomes' => [
                    'Master the end-to-end product management lifecycle.',
                    'Develop and execute data-driven product roadmaps.',
                    'Conduct thorough market and competitor analysis.',
                    'Write professional-grade PRDs and User Stories.',
                    'Lead high-performing Agile and Scrum teams.',
                    'Apply data-driven decision making using analytics tools.',
                    'Build a professional PM portfolio with a comprehensive capstone project.',
                ],
                'curriculum' => [
                    ['week' => 1, 'title' => 'The PM Role', 'topics' => ['What is a PM?', 'Product Lifecycle', 'Stakeholder Management']],
                    ['week' => 2, 'title' => 'Product Strategy', 'topics' => ['Vision & Mission', 'Market Research', 'Competitor Analysis']],
                    ['week' => 3, 'title' => 'Customer Discovery', 'topics' => ['User Interviews', 'Personas', 'Identifying Pain Points']],
                    ['week' => 4, 'title' => 'Prioritisation Frameworks', 'topics' => ['RICE', 'Kano Model', 'Opportunity Scoring']],
                    ['week' => 5, 'title' => 'Defining the Product', 'topics' => ['PRDs', 'Writing User Stories', 'Minimum Viable Product (MVP)']],
                    ['week' => 6, 'title' => 'Agile & Execution', 'topics' => ['Scrum Basics', 'Kanban', 'Dealing with Technical Debt']],
                    ['week' => 7, 'title' => 'Product Analytics', 'topics' => ['KPIs & Metrics', 'A/B Testing', 'Retention Analysis']],
                    ['week' => 8, 'title' => 'Growth & Monetisation', 'topics' => ['Acquisition Channels', 'Pricing Strategies', 'Churn Management']],
                    ['week' => 9, 'title' => 'Design for PMs', 'topics' => ['UX Principles', 'Wireframing for PMs', 'Collaborating with Designers']],
                    ['week' => 10, 'title' => 'Soft Skills', 'topics' => ['Conflict Resolution', 'Negotiation', 'Evangelising the Product']],
                ],
                'about_mdx' => "Great products aren't built by accident; they are built by Product Managers who understand the intersection of **business, technology, and user experience**. This **10-week track** is designed to transform you into a strategic leader capable of shipping products that matter.\n\nYou'll learn the frameworks used by top tech companies globally to prioritize features, define strategy, and manage stakeholders. From writing your first **PRD** to analyzing complex **product metrics**, this course provides the technical and commercial toolkit required to succeed in one of tech's most challenging and rewarded roles.",
                'faqs' => [
                    ['question' => 'Do I need to be a programmer to be a PM?', 'answer' => 'No, PMs focus on the "what" and "why", not the "how". However, technical literacy helps.'],
                    ['question' => 'Is this different from project management?', 'answer' => 'Yes. Project management is about delivery schedules and scope; Product management is about strategic value and user needs.'],
                    ['question' => 'How big are the cohorts?', 'answer' => 'Product Management cohorts are capped at 30 to ensure quality feedback on your PRDs.'],
                    ['question' => 'What tools will I learn?', 'answer' => 'Jira, Trello, Mixpanel, and Figma (from a PM perspective).'],
                ],
                'prerequisites' => 'Strong communication skills and an analytical mindset. Business or tech background is helpful but not required.',
            ],
            [
                'slug' => 'project-management',
                'title' => 'Project Management',
                'category' => 'business',
                'description' => 'Become a certified project manager using PMBOK, Agile, and Scrum frameworks. You will learn how to scope, plan, execute, and close projects across industries. The programme prepares you for PMP and CAPM certifications and connects you with hiring partners actively seeking project management talent.',
                'duration_weeks' => 10,
                'format' => 'cohort',
                'price_ngn' => 120000,
                'price_usd' => 80,
                'scholarship_price_ngn' => 12000,
                'is_published' => true,
                'is_featured' => false,
                'tools_and_technologies' => [
                    ['name' => 'Asana', 'logo_url' => '/logos/asana.svg'],
                    ['name' => 'Monday.com', 'logo_url' => '/logos/monday.svg'],
                    ['name' => 'Jira', 'logo_url' => '/logos/jira.svg'],
                    ['name' => 'Trello', 'logo_url' => '/logos/trello.svg'],
                    ['name' => 'MS Project', 'logo_url' => '/logos/msproject.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Project Manager', 'nigeria_ngn' => '₦6M - ₦11M', 'us_usd' => '$90,000 - $135,000', 'global_usd' => '$110,000'],
                    ['role' => 'Scrum Master', 'nigeria_ngn' => '₦6M - ₦10M', 'us_usd' => '$95,000 - $130,000', 'global_usd' => '$115,000'],
                ],
                'outcomes' => [
                    'Master industry-standard project management methodologies.',
                    'Design and implement comprehensive project plans and budgets.',
                    'Identify and mitigate complex project risks.',
                    'Lead cross-functional teams to successful project delivery.',
                    'Master project management tools including Jira and Asana.',
                    'Demonstrate proficiency in stakeholder communication and management.',
                    'Prepare thoroughly for the PMP certification exam.',
                ],
                'curriculum' => [
                    ['week' => 1, 'title' => 'Project Management 101', 'topics' => ['Project Lifecycle', 'Triple Constraint', 'Role of a PM']],
                    ['week' => 2, 'title' => 'Waterfall Methodology', 'topics' => ['Planning Phase', 'WBS', 'Gantt Charting']],
                    ['week' => 3, 'title' => 'Agile & Scrum', 'topics' => ['Sprint Planning', 'Daily Standups', 'Retrospectives']],
                    ['week' => 4, 'title' => 'Resource Management', 'topics' => ['Budgeting Basics', 'Procurement', 'Team Allocations']],
                    ['week' => 5, 'title' => 'Risk Management', 'topics' => ['Risk Identification', 'Mitigation Strategies', 'Contingency Planning']],
                    ['week' => 6, 'title' => 'Stakeholder Management', 'topics' => ['Communication Plans', 'Negotiation Skills', 'Reporting']],
                    ['week' => 7, 'title' => 'Tools Mastery: Jira', 'topics' => ['Creating Backlogs', 'Tracking Progress', 'Jira Reporting']],
                    ['week' => 8, 'title' => 'Quality Management', 'topics' => ['QA Processes', 'Change Control', 'Closing Projects']],
                    ['week' => 9, 'title' => 'PMP Prep I', 'topics' => ['Ethics & Professionalism', 'Exam Structure', 'Domain Reviews']],
                    ['week' => 10, 'title' => 'PMP Prep II', 'topics' => ['Practice Exams', 'Tips & Tricks', 'Final Project Review']],
                ],
                'about_mdx' => "Projects fail because they aren't managed; they are merely 'done'. This **10-week programme** provides the rigorous framework required to ensure project success across any industry. \n\nFrom the traditional **Waterfall** approach used in construction to the **Agile** workflows dominant in the tech sector, you'll learn to lead teams with confidence and precision. You'll master the mathematical foundations of budgeting and the human art of stakeholder management, ensuring you are ready to deliver value on time and under budget.",
                'faqs' => [
                    ['question' => 'Is this only for tech?', 'answer' => 'No, project management is a universal skill applicable to construction, health, and government.'],
                    ['question' => 'Does this include the PMP exam?', 'answer' => 'No, but the curriculum is specifically designed to prepare you for the PMP exam.'],
                    ['question' => 'Will we use MS Project?', 'answer' => 'Yes, we cover MS Project as part of the Waterfall module.'],
                    ['question' => 'Do I need a degree?', 'answer' => 'No degree is required, though it often helps with PMP eligibility requirements.'],
                    ['question' => 'Is there a focus on Budgeting?', 'answer' => 'Yes, financial management is a core part of the track.'],
                ],
                'prerequisites' => 'Highly organised with excellent written and verbal communication skills.',
            ],
            [
                'slug' => 'virtual-assistant',
                'title' => 'Virtual Assistant',
                'category' => 'business',
                'description' => 'Launch a career as a professional virtual assistant serving clients globally. You will learn executive assistance, calendar management, email management, bookkeeping basics, social media management, and tools like Notion, Asana, and Slack. Wenza VA graduates earn $800–$2,500 per month working remotely.',
                'duration_weeks' => 8,
                'format' => 'cohort',
                'price_ngn' => 90000,
                'price_usd' => 60,
                'scholarship_price_ngn' => 9000,
                'is_published' => true,
                'is_featured' => false,
                'tools_and_technologies' => [
                    ['name' => 'Google Workspace', 'logo_url' => '/logos/google.svg'],
                    ['name' => 'Slack', 'logo_url' => '/logos/slack.svg'],
                    ['name' => 'Notion', 'logo_url' => '/logos/notion.svg'],
                    ['name' => 'Calendly', 'logo_url' => '/logos/calendly.svg'],
                    ['name' => 'Zoom', 'logo_url' => '/logos/zoom.svg'],
                    ['name' => 'QuickBooks', 'logo_url' => '/logos/quickbooks.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Virtual Assistant', 'nigeria_ngn' => '₦2M - ₦5M', 'us_usd' => '$35,000 - $65,000', 'global_usd' => '$48,000'],
                    ['role' => 'Executive Assistant', 'nigeria_ngn' => '₦3M - ₦6M', 'us_usd' => '$45,000 - $75,000', 'global_usd' => '$55,000'],
                ],
                'outcomes' => [
                    'Master professional-level administrative support in a remote context.',
                    'Manage executive calendars and complex scheduling workflows.',
                    'Conduct professional social media management for business clients.',
                    'Perform basic bookkeeping and invoicing using cloud software.',
                    'Build and launch a professional Virtual Assistant freelance business.',
                    'Master the tools required for remote work (Slack, Google Workspace, Zoom).',
                    'Implement effective client relationship management strategies.',
                ],
                'curriculum' => [
                    ['week' => 1, 'title' => 'Remote Work Foundations', 'topics' => ['The VA Mindset', 'Digital Literacy', 'Setting up your Workspace']],
                    ['week' => 2, 'title' => 'Admin Mastery', 'topics' => ['Email Management', 'File Organisation', 'Calendar & Scheduling']],
                    ['week' => 3, 'title' => 'Business Tools', 'topics' => ['Google Workspace Deep Dive', 'CRM Basics (HubSpot)', 'Task Management']],
                    ['week' => 4, 'title' => 'Social & Visuals', 'topics' => ['Basic Social Media MGMT', 'Graphics with Canva', 'Content Scheduling']],
                    ['week' => 5, 'title' => 'Financials & Ethics', 'topics' => ['Basic Bookkeeping', 'Invoicing Tools', 'Data Privacy & Ethics']],
                    ['week' => 6, 'title' => 'Business of VA', 'topics' => ['Finding Clients', 'Pricing your Services', 'Onboarding & Contracts']],
                ],
                'about_mdx' => "The world is going remote, and businesses everywhere need skilled support. This **6-week track** is a practical guide to launching a lucrative career as an **Executive Virtual Assistant**.\n\nYou'll move beyond simple data entry to become a high-value strategic partner. We teach you the tools of the trade—from **Google Workspace** to **HubSpot CRM**—and the soft skills required to work seamlessly with international executives. \n\nBy graduation, you'll have a professional portfolio and a clear plan to land your first client paying in hard currency.",
                'faqs' => [
                    ['question' => 'How quickly can I find clients?', 'answer' => 'Many students land their first freelance client before the 8-week cohort is finished.'],
                    ['question' => 'Is a laptop absolutely necessary?', 'answer' => 'Yes. While some tasks can be done on mobile, a VA requires a computer for full productivity.'],
                    ['question' => 'Does Wenza hire VAs?', 'answer' => 'We occasionally hire from our top graduates, but our focus is teaching you to freelance globally.'],
                    ['question' => 'Can I do this part-time?', 'answer' => 'Yes, this track is specially designed for working professionals looking to pivot.'],
                    ['question' => 'Is English proficiency important?', 'answer' => 'Yes, excellent written and spoken English is critical for international clients.'],
                ],
                'prerequisites' => 'Basic computer literacy, fluency in English, and strong organisational skills.',
            ],
            [
                'slug' => 'digital-marketing',
                'title' => 'Digital Marketing',
                'category' => 'business',
                'description' => 'Drive real business growth through digital channels. This programme covers SEO, Google Ads, Meta advertising, email marketing, marketing analytics, and conversion optimisation. You will manage a live ad campaign during the course, giving you verifiable proof of results for your portfolio.',
                'duration_weeks' => 10,
                'format' => 'cohort',
                'price_ngn' => 120000,
                'price_usd' => 80,
                'scholarship_price_ngn' => 12000,
                'is_published' => true,
                'is_featured' => false,
                'tools_and_technologies' => [
                    ['name' => 'Google Ads', 'logo_url' => '/logos/googleads.svg'],
                    ['name' => 'Meta Ads', 'logo_url' => '/logos/meta.svg'],
                    ['name' => 'Google Analytics', 'logo_url' => '/logos/analytics.svg'],
                    ['name' => 'Mailchimp', 'logo_url' => '/logos/mailchimp.svg'],
                    ['name' => 'SEMrush', 'logo_url' => '/logos/semrush.svg'],
                    ['name' => 'HubSpot', 'logo_url' => '/logos/hubspot.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Digital Marketer', 'nigeria_ngn' => '₦3M - ₦7M', 'us_usd' => '$55,000 - $95,000', 'global_usd' => '$72,000'],
                    ['role' => 'Performance Marketer', 'nigeria_ngn' => '₦4M - ₦8.5M', 'us_usd' => '$65,000 - $110,000', 'global_usd' => '$80,000'],
                ],
                'outcomes' => [
                    'Design and execute data-driven digital marketing strategies.',
                    'Manage and scale profitable ad campaigns on Meta and Google Ads.',
                    'Master SEO fundamentals including on-page and technical audits.',
                    'Build and automate high-converting email marketing funnel.',
                    'Synthesize complex marketing data into actionable growth insights.',
                    'Create compelling content strategies for brand engagement.',
                    'Manage real marketing budgets and deliver measurable ROI.',
                ],
                'curriculum' => [
                    ['week' => 1, 'title' => 'Marketing Foundations', 'topics' => ['Consumer Psychology', 'The Marketing Funnel', 'USP Branding']],
                    ['week' => 2, 'title' => 'Content & Social', 'topics' => ['Content Strategy', 'Social Media Algorithms', 'Community Building']],
                    ['week' => 3, 'title' => 'Search Engine Opt (SEO)', 'topics' => ['Keyword Research', 'On-page SEO', 'Backlink Strategies']],
                    ['week' => 4, 'title' => 'Google Ads (SEM)', 'topics' => ['Campaign Structure', 'Bidding Strategies', 'Search Ads mastery']],
                    ['week' => 5, 'title' => 'Paid Social (Meta Ads)', 'topics' => ['Audience Targeting', 'Creative Best Practices', 'iOS14 Tracking']],
                    ['week' => 6, 'title' => 'Email Marketing', 'topics' => ['Building Lists', 'Email Automations', 'A/B Testing Subject Lines']],
                    ['week' => 7, 'title' => 'Analytics & Data', 'topics' => ['GA4 Setup', 'Tracking Events', 'Attribution Models']],
                    ['week' => 8, 'title' => 'Strategy & Budgeting', 'topics' => ['Projections', 'Media Buying', 'Scaling Winners']],
                    ['week' => 9, 'title' => 'Client Management', 'topics' => ['Reporting Results', 'Pitching Strategies', 'Freelance Marketing']],
                    ['week' => 10, 'title' => 'Final Capstone', 'topics' => ['Live Campaign Launch', 'Data Analysis', 'Final Showdown']],
                ],
                'about_mdx' => "Marketing is the heartbeat of any business. This **10-week programme** takes you deep into the mechanics of **growth and acquisition** in the digital era.\n\nYou won't just learn theory; you'll get your hands dirty with real **Ad budgets**. You'll master the art of SEO, the science of paid media, and the data-driven world of analytics. Whether you're an entrepreneur looking to scale your business or a professional looking to join a high-growth startup, this track provides the full-stack marketing toolkit requested by top employers.",
                'faqs' => [
                    ['question' => 'Do I need to spend my own money on ads?', 'answer' => 'Wenza provides a small sandbox budget for learning, but professional certification requires managing real spend.'],
                    ['question' => 'Is this course focused on strategy or execution?', 'answer' => 'Both. You will learn the high-level strategy and the button-clicks required to execute it.'],
                    ['question' => 'Can I use this for my own business?', 'answer' => 'Absolutely. It is highly recommended for entrepreneurs wanting to drive sales.'],
                    ['question' => 'Is there a focus on SEO?', 'answer' => 'Yes, SEO is a core part of the organic growth module.'],
                    ['question' => 'Will I learn Meta Ads?', 'answer' => 'Yes, Meta (Facebook and Instagram) ads are covered extensively.'],
                    ['question' => 'Do I need prior experience?', 'answer' => 'No, we start from marketing fundamentals.'],
                ],
                'prerequisites' => 'A basic understanding of social media platforms and an interest in consumer behaviour.',
            ],

            // Security
            [
                'slug' => 'cybersecurity',
                'title' => 'Cybersecurity',
                'category' => 'security',
                'description' => 'Train as a professional cybersecurity analyst defending against the attacks that cost African businesses billions annually. Over four months you will cover networking and Linux foundations, defensive security (Splunk, Wazuh, Wireshark), offensive security (Kali Linux, Metasploit, OWASP Top 10), and a "Defend & Respond" capstone. Graduates earn ₦6M–₦10M annually.',
                'duration_weeks' => 16,
                'format' => 'cohort',
                'price_ngn' => 180000,
                'price_usd' => 120,
                'scholarship_price_ngn' => 18000,
                'is_published' => true,
                'is_featured' => true,
                'tools_and_technologies' => [
                    ['name' => 'Linux', 'logo_url' => '/logos/linux.svg'],
                    ['name' => 'Wireshark', 'logo_url' => '/logos/wireshark.svg'],
                    ['name' => 'Splunk', 'logo_url' => '/logos/splunk.svg'],
                    ['name' => 'Kali Linux', 'logo_url' => '/logos/kali.svg'],
                    ['name' => 'Metasploit', 'logo_url' => '/logos/metasploit.svg'],
                    ['name' => 'Wazuh', 'logo_url' => '/logos/wazuh.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Cybersecurity Analyst', 'nigeria_ngn' => '₦6M - ₦10M', 'us_usd' => '$90,000 - $135,000', 'global_usd' => '$145,000'],
                    ['role' => 'SOC Analyst', 'nigeria_ngn' => '₦5M - ₦9M', 'us_usd' => '$85,000 - $120,000', 'global_usd' => '$130,000'],
                ],
                'outcomes' => [
                    'Master professional-level network security and protocol analysis.',
                    'Conduct thorough vulnerability assessments and penetration tests.',
                    'Implement end-to-end security protocols for cloud and local systems.',
                    'Execute professional incident response and forensic procedures.',
                    'Manage security compliance projects for corporate clients.',
                    'Demonstrate proficiency in ethical hacking using industry tools.',
                    'Prepare thoroughly for CompTIA Security+ certification.',
                ],
                'curriculum' => [
                    ['week' => 1, 'title' => 'Security Foundations', 'topics' => ['The CIA Triad', 'Threat Landscapes', 'Risk Management']],
                    ['week' => 2, 'title' => 'Networking for Security', 'topics' => ['OSI Model Deep Dive', 'TCP/IP Security', 'DNS Security']],
                    ['week' => 3, 'title' => 'Linux for Security', 'topics' => ['Kali Linux Overview', 'Shell Persistence', 'Hardening Systems']],
                    ['week' => 4, 'title' => 'Network Attacks', 'topics' => ['Packet Sniffing', 'MITM Attacks', 'Wireshark Analysis']],
                    ['week' => 5, 'title' => 'Vulnerability Assessment', 'topics' => ['Nmap/Nessus Scanning', 'Identifying Exploits', 'Risk Scoring']],
                    ['week' => 6, 'title' => 'Web Security I', 'topics' => ['OWASP Top 10', 'Injections', 'Burp Suite Basics']],
                    ['week' => 7, 'title' => 'Web Security II', 'topics' => ['XSS & CSRF', 'Auth Vulnerabilities', 'API Security']],
                    ['week' => 8, 'title' => 'Endpoint Security', 'topics' => ['Firewalls & IDS', 'Malware Analysis Basics', 'IAM Strategies']],
                    ['week' => 10, 'title' => 'Cryptography', 'topics' => ['Hashing vs Encryption', 'SSL/TLS', 'Public Key Infra (PKI)']],
                    ['week' => 11, 'title' => 'Incident Response', 'topics' => ['Forensics Bases', 'Evidence Collection', 'Recovery Plans']],
                    ['week' => 12, 'title' => 'Compliance & Auditing', 'topics' => ['ISO27001 Foundation', 'GDPR/NDPR Compliance', 'Audit Reports']],
                    ['week' => 13, 'title' => 'Ethical Hacking Lab', 'topics' => ['CTF Challenges', 'Full Exploitation Chain', 'Remediation Reports']],
                    ['week' => 14, 'title' => 'Certification Prep', 'topics' => ['Security+ Exam Review', 'Practice Tests', 'Career Guidance']],
                ],
                'about_mdx' => "The digital world is under constant attack. This **14-week track** transforms you into a guardian of the digital frontier. \n\nYou'll learn the techniques used by malicious actors—not to cause harm, but to build impenetrable defenses. From **Ethical Hacking** to **Digital Forensics**, we provide a deep, technical dive into the world of Cybersecurity. This track is designed for the serious professional looking to join the elite ranks of security specialists who protect the world's most sensitive data.",
                'faqs' => [
                    ['question' => 'Is hacking legal?', 'answer' => 'We teach ethical hacking (white-hat) strictly for defensive purposes and against authorised targets in a lab environment.'],
                    ['question' => 'Do I need a powerful computer?', 'answer' => 'You will need at least 8GB (preferably 16GB) of RAM to run virtual machines smoothly.'],
                    ['question' => 'Will this prepare me for CompTIA Sec+?', 'answer' => 'Yes, the curriculum maps strongly to the CompTIA Security+ certification objectives.'],
                    ['question' => 'Is this a coding course?', 'answer' => 'Yes, you will learn some Python and Bash for security automation.'],
                    ['question' => 'Is there a focus on African security?', 'answer' => 'Yes, we cover NDPR and other local compliance frameworks.'],
                    ['question' => 'Is this course only for pros?', 'answer' => 'We start from foundations, but a basic understanding of computer networking is required.'],
                ],
                'prerequisites' => 'Solid understanding of computer networking and operating systems.',
            ],

            // Cloud Engineering
            [
                'slug' => 'cloud-engineering',
                'title' => 'Cloud Engineering',
                'category' => 'engineering',
                'description' => 'Design, build, and manage scalable cloud infrastructure on AWS and Azure. This programme covers cloud architecture, serverless computing, containerisation with Docker and Kubernetes, infrastructure-as-code with Terraform, and cost optimisation. Graduates are prepared for AWS Solutions Architect and Azure Administrator certifications.',
                'duration_weeks' => 14,
                'format' => 'cohort',
                'price_ngn' => 170000,
                'price_usd' => 115,
                'scholarship_price_ngn' => 17000,
                'is_published' => true,
                'is_featured' => false,
                'tools_and_technologies' => [
                    ['name' => 'AWS', 'logo_url' => '/logos/aws.svg'],
                    ['name' => 'Azure', 'logo_url' => '/logos/azure.svg'],
                    ['name' => 'Terraform', 'logo_url' => '/logos/terraform.svg'],
                    ['name' => 'Docker', 'logo_url' => '/logos/docker.svg'],
                    ['name' => 'Kubernetes', 'logo_url' => '/logos/kubernetes.svg'],
                    ['name' => 'Linux', 'logo_url' => '/logos/linux.svg'],
                ],
                'career_outcomes' => [
                    ['role' => 'Cloud Engineer', 'nigeria_ngn' => '₦7M - ₦13M', 'us_usd' => '$105,000 - $160,000', 'global_usd' => '$145,000'],
                    ['role' => 'Cloud Solutions Architect', 'nigeria_ngn' => '₦9M - ₦16M', 'us_usd' => '$120,000 - $180,000', 'global_usd' => '$155,000'],
                ],
                'outcomes' => [
                    'Master professional-level cloud architecture on AWS and GCP.',
                    'Design and implement resilient, scalable cloud systems.',
                    'Secure complex cloud environments using advanced IAM.',
                    'Perform large-scale cloud migrations for enterprise clients.',
                    'Optimise cloud infrastructure for maximum cost-effectiveness.',
                    'Deploy serverless and containerized architectures at scale.',
                    'Master Infrastructure as Code (IaC) workflows.',
                ],
                'curriculum' => [
                    ['week' => 1, 'title' => 'Cloud Foundations', 'topics' => ['What is Cloud?', 'Shared Responsibility Model', 'Economics of Cloud']],
                    ['week' => 2, 'title' => 'AWS Deep Dive I', 'topics' => ['EC2 Instances', 'S3 Storage', 'VPC Networking Basics']],
                    ['week' => 3, 'title' => 'AWS Deep Dive II', 'topics' => ['RDS & DynamoDB', 'IAM Policies', 'Route53 DNS']],
                    ['week' => 4, 'title' => 'Google Cloud (GCP)', 'topics' => ['Compute Engine', 'Cloud Storage', 'GCP Identity Basics']],
                    ['week' => 5, 'title' => 'Cloud Security', 'topics' => ['WAF & Shield', 'Key Management (KMS)', 'Cloud Auditing']],
                    ['week' => 6, 'title' => 'Cloud Migration', 'topics' => ['Migration Strategies (6 Rs)', 'Database Migration Service (DMS)']],
                    ['week' => 7, 'title' => 'Serverless Computing', 'topics' => ['AWS Lambda', 'Cloud Functions', 'Event-driven Design']],
                    ['week' => 8, 'title' => 'Containers on Cloud', 'topics' => ['ECS & EKS Basics', 'GKE Foundations', 'Artifact Registries']],
                    ['week' => 9, 'title' => 'Infrastructure as Code', 'topics' => ['CloudFormation vs Terraform', 'Managing TF State']],
                    ['week' => 10, 'title' => 'Cost Management (FinOps)', 'topics' => ['CloudWatch/GCP Monitoring', 'Cost Explorer', 'Optimization']],
                    ['week' => 11, 'title' => 'Disaster Recovery', 'topics' => ['Backup Strategies', 'High Availability Design', 'Multi-region Architectures']],
                    ['week' => 12, 'title' => 'Final Capstone', 'topics' => ['Architecture Proposal', 'Hands-on Deployment', 'Viva Voce']],
                ],
                'about_mdx' => "The cloud is no longer the future; it is the present. This **12-week track** provides the architectural and technical expertise required to build, manage, and secure the modern web's infrastructure.\n\nYou'll move beyond clicking buttons in the dashboard to building automated, programmable infrastructure using **Terraform** and **CloudFormation**. We cover the major providers—**AWS, GCP, and Azure**—ensuring you are an adaptable, cloud-agnostic professional. Graduates are ready for top-tier roles as Cloud Architects and Systems Engineers in the global tech ecosystem.",
                'faqs' => [
                    ['question' => 'How is this different from DevOps?', 'answer' => 'Cloud Engineering focuses heavily on architectural design and cloud-native services, while DevOps focuses more on CI/CD pipelines and deployment automation. There is overlap.'],
                    ['question' => 'Which cloud provider do we focus on?', 'answer' => 'The curriculum is heavily weighted heavily towards AWS, but covers multi-cloud concepts and Azure foundations.'],
                    ['question' => 'Is this a beginner course?', 'answer' => 'No. You should have a solid grasp of basic networking, Linux, and general computing concepts before starting.'],
                    ['question' => 'Will I get AWS certified?', 'answer' => 'The course prepares you for AWS Solutions Architect Associate, but the exam fee is not included.'],
                    ['question' => 'How much math is involved?', 'answer' => 'Basic arithmetic and a strong sense of logic/architecture are needed.'],
                ],
                'prerequisites' => 'Fundamental understanding of networking (TCP/IP), Linux command line, and basic scripting.',
            ],
        ];

        foreach ($courses as $courseData) {
            $course = Course::updateOrCreate(
                ['slug' => $courseData['slug']],
                $courseData
            );

        }
    }
}
